### ISSUE TITLE
OSError: [Errno 16] Device or resource busy: '.nfs00000000160c011a00063458'

### ISSUE THREAD

**Issue by wylqq312715289** [modelscope/modelscope#104]
Traceback (most recent call last):
  File "/***/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "//***/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "//***/.pyenv/versions/3.7.3/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "//***/.pyenv/versions/3.7.3/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "//***/.pyenv/versions/3.7.3/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000160c011a00063458'

**Comment by yingdachen** [comment]
looks like general python-env issue and not modelscope-specific.

if you can provide more info regarding how this issue is produced, we can try to help diagnosis.
