### ISSUE TITLE
"BUG" modelscope在线模型不能批量推理预测

### ISSUE THREAD

**Issue by xiabingbao-ok** [modelscope/modelscope#110]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('named-entity-recognition', 'damo/nlp_raner_named-entity-recognition_chinese-base-ecom')
res = p(['欧美单 秋季女装时尚百搭休闲修身 亚麻混纺短款 外套西装', '亚麻混纺短款 外套西装'], batch_size=2)
print(res)

错误如下：
Traceback (most recent call last):
  File "dianshang.py", line 5, in <module>
    res = p(['欧美单 秋季女装时尚百搭休闲修身 亚麻混纺短款 外套西装', '亚麻混纺短款 外套西装'], batch_size=2)
  File "/opt/anaconda3/envs/xjms/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 177, in __call__
    output = self._process_batch(input, batch_size, **kwargs)
  File "/opt/anaconda3/envs/xjms/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 258, in _process_batch
    out = self._batch(preprocessed_list)
  File "/opt/anaconda3/envs/xjms/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 235, in _batch
    batch_data[k] = torch.cat(batch_data[k])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 30 but got size 13 for tensor number 1 in the list.

**Comment by xiabingbao-ok** [comment]
找到原因了

**Comment by GaoXinJian-USTC** [comment]
> 找到原因了

怎么解决的？
