### ISSUE TITLE
Cannot read llava onevision checkpoint using AutoModelForCausalLM

### ISSUE THREAD

**Issue by Lopa07** [modelscope/modelscope#1164]
**General Question**
I want to read the modelscope `llava-onevision-qwen2-0.5b-si-hf` checkpoint using transformers library. I followed [this suggestion](https://github.com/modelscope/modelscope/issues/911#issuecomment-2232664978).

Code used:
```
from modelscope import snapshot_download
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = snapshot_download("AI-ModelScope/llava-onevision-qwen2-0.5b-si-hf")

tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()
```

This resulted in the following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/VDIL_COREML/m.banerjee/anaconda3/envs/swift/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava_onevision.configuration_llava_onevision.LlavaOnevisionConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, ElectraConfig, ErnieConfig, FalconConfig, FalconMambaConfig, FuyuConfig, GemmaConfig, Gemma2Config, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GraniteConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, Mamba2Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NemotronConfig, OlmoConfig, OlmoeConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```

Versions:
```
python 3.9.19
modelscope 1.18.0
transformers 4.45.0.dev0
```

Model related:  @tastelikefeet
Model hub related: @liuyhwangyh
Pipeline related: @tastelikefeet @wangxingjun778

**Comment by yingdachen** [comment]
It is not a CausalLM and therefore cannot use AutoModelForCausalLM. If you just want to download the model, simply use


```python
from modelscope import snapshot_download
model_dir = snapshot_download("AI-ModelScope/llava-onevision-qwen2-0.5b-si-hf")
```


Otherwise, you may use the sample code on the model page: https://modelscope.cn/models/AI-ModelScope/llava-onevision-qwen2-0.5b-si-hf

```python
import requests
from PIL import Image

import torch
from transformers import AutoProcessor, LlavaOnevisionForConditionalGeneration
from modelscope import snapshot_download


model_dir = snapshot_download("AI-ModelScope/llava-onevision-qwen2-0.5b-si-hf")
model = LlavaOnevisionForConditionalGeneration.from_pretrained(
    model_dir, 
    torch_dtype=torch.float16, 
    low_cpu_mem_usage=True, 
).to(0)

processor = AutoProcessor.from_pretrained(model_dir)

# Define a chat history and use `apply_chat_template` to get correctly formatted prompt
# Each value in "content" has to be a list of dicts with types ("text", "image") 
conversation = [
    {

      "role": "user",
      "content": [
          {"type": "text", "text": "What are these?"},
          {"type": "image"},
        ],
    },
]
prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)

image_file = "http://images.cocodataset.org/val2017/000000039769.jpg"
raw_image = Image.open(requests.get(image_file, stream=True).raw)
inputs = processor(images=raw_image, text=prompt, return_tensors='pt').to(0, torch.float16)

output = model.generate(**inputs, max_new_tokens=200, do_sample=False)
print(processor.decode(output[0][2:], skip_special_tokens=True))
```

**Comment by Lopa07** [comment]
Thank you!
So instead of `AutoTokenizer` and `AutoModelForCausalLM` should use `AutoProcessor` and `LlavaOnevisionForConditionalGeneration`, respectively.
