### ISSUE TITLE
pipeline实例化时传递device和weights_only在'damo/cv_unet-image-face-fusion_damo'模型使用时无效

### ISSUE THREAD

**Issue by jinxiangwzh** [modelscope/modelscope#1165]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
在本地运行人脸融合示例，报错，运行代码：
import os

import cv2
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

image_face_fusion = pipeline(Tasks.image_face_fusion,
                             model='damo/cv_unet-image-face-fusion_damo', device='cpu', weights_only=True)
template_path = 'https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/facefusion_template.jpg'
user_path = 'https://modelscope.oss-cn-beijing.aliyuncs.com/test/images/facefusion_user.jpg'
result = image_face_fusion(dict(template=template_path, user=user_path))

cv2.imwrite('result.png', result[OutputKeys.OUTPUT_IMG])
print('finished!')
报错：
2024-12-31 08:46:16,776 - modelscope - WARNING - Model revision not specified, use revision: v1.3
2024-12-31 08:46:17,126 - modelscope - INFO - initiate model from C:\Users\bm-wuzhaohua\.cache\modelscope\hub\damo\cv_unet-image-face-fusion_damo
2024-12-31 08:46:17,127 - modelscope - INFO - initiate model from location C:\Users\bm-wuzhaohua\.cache\modelscope\hub\damo\cv_unet-image-face-fusion_damo.
2024-12-31 08:46:17,130 - modelscope - INFO - initialize model from C:\Users\bm-wuzhaohua\.cache\modelscope\hub\damo\cv_unet-image-face-fusion_damo
C:\Program Files\Python312\Lib\site-packages\torch\functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3596.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\image_face_fusion.py:57: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoints = torch.load(model_path, map_location='cpu')
C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\image_face_fusion.py:67: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(arcface_path, map_location='cpu'), strict=False)
C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\image_face_fusion.py:74: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(f_3d_path, map_location='cpu')['net_recon'])
WARNING:tensorflow:From C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\face_detection\peppa_pig_face\face_detector.py:98: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2024-12-31 08:46:25.034224: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\face_detection\peppa_pig_face\face_detector.py:103: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2024-12-31 08:46:25,192 - modelscope - INFO - load facefusion models done
C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\facegan\face_gan.py:27: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pretrained_dict = torch.load(self.mfile)
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
           ^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\image_face_fusion.py", line 97, in __init__
    self.ganwrap_1024 = GPEN(face_enhance_path, 1024, 2, self.device)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\facegan\face_gan.py", line 22, in __init__
    self.load_model(channel_multiplier)
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\cv\image_face_fusion\facegan\face_gan.py", line 27, in load_model
    pretrained_dict = torch.load(self.mfile)
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 1360, in load
    return _load(
           ^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 1848, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 1812, in persistent_load
    typed_storage = load_tensor(
                    ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 1784, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 601, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 539, in _deserialize
    device = _validate_device(location, backend_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\torch\serialization.py", line 508, in _validate_device
    raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\pipelines\cv\image_face_fusion_pipeline.py", line 43, in __init__
    super().__init__(model=model, **kwargs)
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: ImageFaceFusion: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\test\gradio\test_face_fusion.py", line 10, in <module>
    image_face_fusion = pipeline(Tasks.image_face_fusion,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\pipelines\builder.py", line 169, in pipeline
    return build_pipeline(cfg, task_name=task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: ImageFaceFusionPipeline: ImageFaceFusion: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Process finished with exit code 1

Please @ corresponding people according to your problem:

Model related:  @tastelikefeet

Model hub related: @liuyhwangyh @tastelikefeet @wangxingjun778

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @tastelikefeet @wangxingjun778

Contribute your model: @yingdachen

**Comment by yingdachen** [comment]
weights_only=True parameter is ok, but the model/pipeline is not validated on a cpu machine, so you should run it on GPU
