### ISSUE TITLE
GPT3 如何利用pipeline加载已经训练得到的权重文件（.pth格式）？

### ISSUE THREAD

**Issue by 460130107** [modelscope/modelscope#118]
按照官方：

训练完成以后，文件夹中会生成推理用的模型配置，可以直接用于pipeline：

{work_dir}/output：训练完成后，存储模型配置文件，及最后一个epoch/iter的模型参数（配置中需要指定CheckpointHook）
{work_dir}/output_best：最佳模型参数时，存储模型配置文件，及最佳的模型参数（配置中需要指定BestCkptSaverHook）

from modelscope.pipelines import pipeline
pipeline_ins = pipeline('text-classification', model='/tmp/output')
pipeline_ins(('这个功能可用吗', '这个功能现在可用吗'))

GPT3会报错

Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/knodi_tagger/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/omnisky/anaconda3/envs/knodi_tagger/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/omnisky/anaconda3/envs/knodi_tagger/lib/python3.7/site-packages/modelscope/pipelines/nlp/distributed_gpt3_pipeline.py", line 39, in _instantiate_one
    cls.model = DistributedGPT3(model_dir, rank, **kwargs)
  File "/home/omnisky/anaconda3/envs/knodi_tagger/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/distributed_gpt3.py", line 997, in __init__
    load_model = pre_load(ckpt_rank, model_dir, tag=path_load_tag)
  File "/home/omnisky/anaconda3/envs/knodi_tagger/lib/python3.7/site-packages/modelscope/utils/nlp/load_checkpoint.py", line 69, in pre_load
    return checkpoint['module']
KeyError: 'module'

**Comment by wylqq312715289** [comment]
如果单机多卡，会出现矩阵的shape mismatch的问题。

**Comment by wenmengzhou** [comment]
1.3.0 版本中 tensor 并行训练过程中每次保存 ckpt 都会保存对应训练线程数的 pth 文件，文件名中带有 rank_0x 信息，将这些 pth 文件重命名为 mp_rank_0x_model_states.pt 放入 <model_id>/model 路径下即可使用

**Comment by 460130107** [comment]
> 

1.3版本测试了，还是报上面的错误

**Comment by wenmengzhou** [comment]
> 1.3版本测试了，还是报上面的错误

It has been fixed in version 1.4
