### ISSUE TITLE
gpt3 2.3b 训练 loss nan 

### ISSUE THREAD

**Issue by kunshou123** [modelscope/modelscope#120]
![image](https://user-images.githubusercontent.com/38267683/219998459-40a23e7b-913f-4771-beea-431714f4c1f2.png)
训练环境：pytorch 1.7.1 +cuda11.0 batchsize 修改为了 2
python -m torch.distributed.launch --nproc_per_node=2 --master_port 29501 gpt3.py
![image](https://user-images.githubusercontent.com/38267683/219998682-77ada962-4e50-4e72-a6d5-fe84246fcf81.png)

**Comment by Firmament-cyou** [comment]
您好，请问您训练使用的模型是1.3B还是2.7B？训练使用的脚本或是具体的训练超参能否提供一下？

**Comment by kunshou123** [comment]
> 您好，请问您训练使用的模型是1.3B还是2.7B？训练使用的脚本或是具体的训练超参能否提供一下？
您好，用的是1.3B的开源模型，脚本就是用的modelscope上开源的训练脚本，Dureader问题生成数据集上二次开发训练，超参只把batchsize 改小了为了2。
```
https://modelscope.cn/models/damo/nlp_gpt3_text-generation_1.3B/summary 
```
另外发现测试的时候也有错误
```
 y: 15831, loss: nan
Total test samples: 100%|████████████████████████████████████████████████████████████████████████████████████| 1417/1417 [3:56:20<00:00, 10.01s/it]
Traceback (most recent call last):
  File "gpt3.py", line 65, in <module>
    trainer.train()
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 543, in train
    self.train_loop(self.train_dataloader)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1030, in train_loop
    self.invoke_hook(TrainerStages.after_train_epoch)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1167, in invoke_hook
    getattr(hook, fn_name)(self)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 35, in after_train_epoch
    self.do_evaluate(trainer)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 47, in do_evaluate
    eval_res = trainer.evaluate()
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 623, in evaluate
    metric_classes)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1091, in evaluation_loop
    data_loader_iters=self._eval_iters_per_epoch)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/utils/inference.py", line 77, in single_gpu_test
    return get_metric_values(metric_classes)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/utils/inference.py", line 194, in get_metric_values
    metric_values.update(metric_cls.evaluate())
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/metrics/text_generation_metric.py", line 53, in evaluate
Total test samples: 100%|████████████████████████████████████████████████████████████████████████████████████| 1417/1417 [3:56:20<00:00, 10.01s/it]
Traceback (most recent call last):
  File "gpt3.py", line 65, in <module>
    trainer.train()
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 543, in train
    self.train_loop(self.train_dataloader)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1030, in train_loop
    self.invoke_hook(TrainerStages.after_train_epoch)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1167, in invoke_hook
    getattr(hook, fn_name)(self)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 35, in after_train_epoch
    self.do_evaluate(trainer)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 47, in do_evaluate
    eval_res = trainer.evaluate()
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 623, in evaluate
    metric_classes)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1091, in evaluation_loop
    data_loader_iters=self._eval_iters_per_epoch)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/utils/inference.py", line 77, in single_gpu_test
    return get_metric_values(metric_classes)
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/trainers/utils/inference.py", line 194, in get_metric_values
    metric_values.update(metric_cls.evaluate())
  File "/root/miniconda3/lib/python3.7/site-packages/modelscope/metrics/text_generation_metric.py", line 53, in evaluate
    preds, tgts = zip(*tmp)
ValueError: not enough values to unpack (expected 2, got 0)
    preds, tgts = zip(*tmp)
ValueError: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-u', 'gpt3.py', '--local_rank=1']' returned non-zero exit status 1.
```

**Comment by Firmament-cyou** [comment]
您好，我使用多卡 32g 显存的 v100 机器分别在 2/4/8 的tensor 并行度上均未复现您出现的问题，nan 问题的可能性很多，可能需要进一步的排查定位。我们将在近几天推出 modelscope==1.3.1 版本，其中进行了一些 gpt 训练相关的修复，您可以在发布后测试新版本中这一问题是否还会出现～

**Comment by kunshou123** [comment]
![image](https://user-images.githubusercontent.com/38267683/221791423-97ed2d50-3894-486e-bd2b-8fca70d6a979.png)


> 您好，我使用多卡 32g 显存的 v100 机器分别在 2/4/8 的tensor 并行度上均未复现您出现的问题，nan 问题的可能性很多，可能需要进一步的排查定位。我们将在近几天推出 modelscope==1.3.1 版本，其中进行了一些 gpt 训练相关的修复，您可以在发布后测试新版本中这一问题是否还会出现～

好的，谢谢，另外,我在另外一个问题中也看见了和我一样并行训练后参数保存的问题，load到单卡的参数只有并行卡数的1/n, 我训练的版本是1.3.0还是存在相应的问题，但是说新版本modelscope 1.3.0已经修复了参数,请问是还没有更新吗

**Comment by yinzhang809** [comment]
不知道楼主有没有改过sequence_length, 我在自己数据集上使用Dureader的脚本发现当样本输入大于sequence_length时会出现loss为nan的情况（训练到一半突然变成nan）

**Comment by Firmament-cyou** [comment]
> 不知道楼主有没有改过sequence_length, 我在自己数据集上使用Dureader的脚本发现当样本长度大于sequence_length时会出现loss为nan的情况（训练到一半突然变成nan） modelscope==1.3.2

您好，我们正在尝试复现您遇到的 nan 问题，您可以先使用较大的 sequence_length 避免样本被截断，感谢您的反馈～
