### ISSUE TITLE
读光-行识别模型运行时报错NameError: name 'math' is not defined

### ISSUE THREAD

**Issue by 717ct** [modelscope/modelscope#126]
今天更新了modelscope版本，运行文字检测+文字识别的demo，使用读光-行识别模型报错，使用读光-crnn识别模型可运行：

代码：
ocr_detection = pipeline(Tasks.ocr_detection, model='damo/cv_resnet18_ocr-detection-line-level_damo')
ocr_recognition = pipeline(Tasks.ocr_recognition, model='damo/cv_convnextTiny_ocr-recognition-general_damo') 
ocr_recognition = pipeline(Tasks.ocr_recognition, model='damo/cv_crnn_ocr-recognition-general_damo') 

报错信息：
0
box: 249.0,730.0,779.0,730.0,779.0,782.0,249.0,782.0
text: 买160ml到手30ml
Traceback (most recent call last):
  File "/Users/ct/PycharmProjects/brand_check/main_ocr.py", line 140, in <module>
    result = ocr_recognition(image_crop)
  File "/Users/ct/opt/anaconda3/envs/modelscope_dg/lib/python3.7/site-packages/modelscope/pipelines/cv/ocr_recognition_pipeline.py", line 62, in __call__
    return super().__call__(input, **kwargs)
  File "/Users/ct/opt/anaconda3/envs/modelscope_dg/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 196, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/Users/ct/opt/anaconda3/envs/modelscope_dg/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 224, in _process_single
    out = self.preprocess(input, **preprocess_params)
  File "/Users/ct/opt/anaconda3/envs/modelscope_dg/lib/python3.7/site-packages/modelscope/pipelines/cv/ocr_recognition_pipeline.py", line 65, in preprocess
    outputs = self.preprocessor(inputs)
  File "/Users/ct/opt/anaconda3/envs/modelscope_dg/lib/python3.7/site-packages/modelscope/models/cv/ocr_recognition/preprocessor.py", line 83, in __call__
    split_batch_cnt = math.ceil((true_w - 48) * 1.0 / 252)
NameError: name 'math' is not defined
1
box: 197.0,131.0,603.0,131.0,603.0,185.0,197.0,185.0
text: 温和净颜不紧绷

Process finished with exit code 1

**Comment by scutyuanzhi** [comment]
你好，这个bug会在2月底的小版本modelscope==1.3.1中修复（预计近期就会发布）。
如果你需要现在使用的话，可以先退回modelscope==1.2.0的版本（该版本中除了damo/cv_crnn_ocr-recognition-general_damo模型，其他都是可以使用的）；或者在本版本modelscope==1.3.0中使用damo/cv_crnn_ocr-recognition-general_damo，这个模型是本版本新上的模型。
