### ISSUE TITLE
RuntimeError: DistributedGPT3Pipeline: Error building extension 'scaled_upper_triang_masked_softmax_cuda'

### ISSUE THREAD

**Issue by adzhua** [modelscope/modelscope#175]
请问调用pipe = pipeline(Tasks.text_generation, model='damo/nlp_gpt3_text-generation_1.3B')时候报：
RuntimeError: DistributedGPT3Pipeline: Error building extension 'scaled_upper_triang_masked_softmax_cuda'
这是什么原因啦

**Comment by yinzhang809** [comment]
我在gcc版本是5.5.0的时候也遇到这个问题，升级到7.5.0就不报错了

**Comment by alexa1109** [comment]
> 我在gcc版本是5.5.0的时候也遇到这个问题，升级到7.5.0就不报错了

请问下，我gcc版本是9.5.0的时候也是报这个错误，降版本就没事了吗

**Comment by yinzhang809** [comment]
> > 我在gcc版本是5.5.0的时候也遇到这个问题，升级到7.5.0就不报错了
> 
> 请问下，我gcc版本是9.5.0的时候也是报这个错误，降版本就没事了吗

不清楚... 你报错里有这个error吗，我是搜这个error 然后根据 https://github.com/NVIDIA/apex/issues/1268 这里的评论解决的。
error: invalid static_cast from type ‘const torch::OrderedDict<std::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::basic_string<char>, at::Tensor>&’

**Comment by alexa1109** [comment]
> > > 我在gcc版本是5.5.0的时候也遇到这个问题，升级到7.5.0就不报错了
> > 
> > 
> > 请问下，我gcc版本是9.5.0的时候也是报这个错误，降版本就没事了吗
> 
> 不清楚... 你报错里有这个error吗，我是搜这个error 然后根据 [NVIDIA/apex#1268](https://github.com/NVIDIA/apex/issues/1268) 这里的评论解决的。 error: invalid static_cast from type ‘const torch::OrderedDict<std::basic_string, at::Tensor>’ to type ‘torch::OrderedDict<std::basic_string, at::Tensor>&’

```
2023-03-09 17:13:52,984 - modelscope - INFO - PyTorch version 1.13.1 Found.
2023-03-09 17:13:52,985 - modelscope - INFO - Loading ast index from /home/administor/.cache/modelscope/ast_indexer
2023-03-09 17:13:53,059 - modelscope - INFO - Loading done! Current index file version is 1.3.0, with md5 6b31106d58f7f9d60747dd9d2e210b7b and a total number of 746 components indexed
2023-03-09 17:13:54,201 - modelscope - INFO - Model revision not specified, use the latest revision: v1.1.0
2023-03-09 17:13:54,401 - modelscope - INFO - File config.json already in cache, skip downloading!
2023-03-09 17:13:54,401 - modelscope - INFO - File configuration.json already in cache, skip downloading!
2023-03-09 17:13:54,401 - modelscope - INFO - File gpt.png already in cache, skip downloading!
2023-03-09 17:13:54,402 - modelscope - INFO - File mp_rank_00_model_states.pt already in cache, skip downloading!
2023-03-09 17:13:54,402 - modelscope - INFO - File README.md already in cache, skip downloading!
2023-03-09 17:13:54,402 - modelscope - INFO - File tokenizer.json already in cache, skip downloading!
2023-03-09 17:13:56,475 - modelscope - INFO - PyTorch version 1.13.1 Found.
2023-03-09 17:13:56,476 - modelscope - INFO - Loading ast index from /home/administor/.cache/modelscope/ast_indexer
2023-03-09 17:13:56,501 - modelscope - INFO - Loading done! Current index file version is 1.3.0, with md5 6b31106d58f7f9d60747dd9d2e210b7b and a total number of 746 components indexed
using world size: 1, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 1 
using torch.float32 for parameters ...
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 42 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 2760 and data parallel seed: 42
> compiling and loading fused kernels ...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF scaled_upper_triang_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /usr/local/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/scaled_upper_triang_masked_softmax.cpp -o scaled_upper_triang_masked_softmax.o 
FAILED: scaled_upper_triang_masked_softmax.o 
c++ -MMD -MF scaled_upper_triang_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /usr/local/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -c /home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/scaled_upper_triang_masked_softmax.cpp -o scaled_upper_triang_masked_softmax.o 
cc1plus: fatal error: /usr/local/cuda-11.7/include/stdc-predef.h: 权限不够
compilation terminated.
[2/3] /usr/local/cuda-11.7/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /usr/local/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o 
FAILED: scaled_upper_triang_masked_softmax_cuda.cuda.o 
/usr/local/cuda-11.7/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/TH -isystem /home/administor/.local/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /usr/local/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o 
cc1plus: fatal error: /usr/local/cuda-11.7/include/stdc-predef.h: 权限不够
compilation terminated.
ninja: build stopped: subcommand failed.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/administor/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.8/site-packages/modelscope/pipelines/nlp/distributed_gpt3_pipeline.py", line 39, in _instantiate_one
    cls.model = DistributedGPT3(model_dir, rank, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/modelscope/models/nlp/gpt3/distributed_gpt3.py", line 976, in __init__
    init_megatron_util(model_dir=model_dir, rank=rank)
  File "/usr/local/lib/python3.8/site-packages/modelscope/utils/megatron_utils.py", line 46, in init_megatron_util
    initialize_megatron(megatron_cfg)
  File "/home/administor/.local/lib/python3.8/site-packages/megatron_util/initialize.py", line 73, in initialize_megatron
    _compile_dependencies()
  File "/home/administor/.local/lib/python3.8/site-packages/megatron_util/initialize.py", line 91, in _compile_dependencies
    fused_kernels.load(args)
  File "/home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/__init__.py", line 71, in load
    scaled_upper_triang_masked_softmax_cuda = _cpp_extention_load_helper(
  File "/home/administor/.local/lib/python3.8/site-packages/megatron_util/fused_kernels/__init__.py", line 47, in _cpp_extention_load_helper
    return cpp_extension.load(
  File "/home/administor/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/administor/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/administor/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/administor/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'scaled_upper_triang_masked_softmax_cuda'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.8/site-packages/modelscope/pipelines/nlp/distributed_gpt3_pipeline.py", line 34, in __init__
    super().__init__(model, preprocessor=preprocessor, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 431, in __init__
    self.model_pool.map(
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: Error building extension 'scaled_upper_triang_masked_softmax_cuda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    pipe = pipeline(Tasks.text_generation, model=model_id)
  File "/usr/local/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 141, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/usr/local/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 54, in build_pipeline
    return build_from_cfg(
  File "/usr/local/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: DistributedGPT3Pipeline: Error building extension 'scaled_upper_triang_masked_softmax_cuda'
```
最后也是报错 RuntimeError: DistributedGPT3Pipeline: Error building extension 'scaled_upper_triang_masked_softmax_cuda'
我也搜过，没看到相关问答

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

$ gcc -v
gcc version 9.5.0 (Ubuntu 9.5.0-1ubuntu1~22.04)

**Comment by yinzhang809** [comment]
> cc1plus: fatal error: /usr/local/cuda-11.7/include/stdc-predef.h: 权限不够

问题应该出在这句吧，改下权限试试 @alexa1109

**Comment by adzhua** [comment]
谢谢，升级后就可以了发自我的荣耀手机-------- 原始邮件 --------发件人： yinzhang809 ***@***.***>日期： 2023年3月9日周四 傍晚6:02收件人： modelscope/modelscope ***@***.***>抄送： adzhua ***@***.***>, Author ***@***.***>主    题： Re: [modelscope/modelscope] RuntimeError: DistributedGPT3Pipeline: Error building extension 'scaled_upper_triang_masked_softmax_cuda' (Issue #175)
我在gcc版本是5.5.0的时候也遇到这个问题，升级到7.5.0就不报错了
