### ISSUE TITLE
RuntimeError: MGLMTextSummarizationPipeline: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500

### ISSUE THREAD

**Issue by alphanlp** [modelscope/modelscope#196]
Traceback (most recent call last):
  File "chinese_abstract.py", line 27, in <module>
    model_revision='v1.0.1',
  File "/data/huap/software/miniconda3/envs/ms/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 141, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/data/huap/software/miniconda3/envs/ms/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 55, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/data/huap/software/miniconda3/envs/ms/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: MGLMTextSummarizationPipeline: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

**Comment by yingdachen** [comment]
看起来是网络不通？

**Comment by yinzhang809** [comment]
是不是同时还有别的类似程序再跑？看样子是端口被别的程序占用了，torchrun 拉起训练的时候 使用--master_port xxxx 改一下端口试试
