### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [modelscope/modelscope#210]
trying to run the following code, ends up with the error.
```
from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys

#device = torch.device('cpu')


p = pipeline('text-to-video-synthesis', 'damo/text-to-video-synthesis')
test_text = {
        'text': 'A panda eating bamboo on a rock.',
    }
output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
print('output_video_path:', output_video_path)
```

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 212, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 247, in _process_single
    out = self.forward(out, **forward_params)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/multi_modal/text_to_video_synthesis_pipeline.py", line 58, in forward
    video = self.model(input)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 34, in __call__
    return self.postprocess(self.forward(*args, **kwargs))
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/multi_modal/video_synthesis/text_to_video_synthesis_model.py", line 167, in forward
    eta=0.0)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/multi_modal/video_synthesis/diffusion.py", line 221, in ddim_sample_loop
    ddim_timesteps, eta)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/multi_modal/video_synthesis/diffusion.py", line 169, in ddim_sample
    percentile, guide_scale)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/multi_modal/video_synthesis/diffusion.py", line 120, in p_mean_variance
    var = _i(self.posterior_variance, t, xt)
  File "/home/sadmin/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/multi_modal/video_synthesis/diffusion.py", line 14, in _i
    return tensor[t].view(shape).to(x)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
I am using an RTX 3060 12GB version, before the whole thing crashes, it uses about 6GB of VRAM.

**Comment by mic2112** [comment]
Hi, I am running into the same error.

**Comment by johndpope** [comment]
I think the python version is too old - same error on python 3.9 - 

conda create -n myenv python=3.11 

pip install cmake
pip install opencv-python  
pip install -r requirements.txt


now I'm seeing
```shell

python test.py    
2023-03-20 22:57:36,821 - modelscope - INFO - PyTorch version 2.0.0 Found.
2023-03-20 22:57:36,822 - modelscope - INFO - Loading ast index from /home/oem/.cache/modelscope/ast_indexer
2023-03-20 22:57:36,874 - modelscope - INFO - No valid ast index found from /home/oem/.cache/modelscope/ast_indexer, generating ast index from prebuilt!
2023-03-20 22:57:36,891 - modelscope - INFO - Loading done! Current index file version is 1.4.1, with md5 74642361be65fa71a54317b7528c45f7 and a total number of 842 components indexed
No module named 'tensorflow'
Fetching 6 files: 100%|███████████████████████████████| 6/6 [00:01<00:00,  4.82it/s]
2023-03-20 22:57:40,301 - modelscope - INFO - initiate model from weights
2023-03-20 22:57:40,301 - modelscope - INFO - initiate model from location weights.
2023-03-20 22:57:40,302 - modelscope - INFO - initialize model from weights
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
           ^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/pipelines/multi_modal/text_to_video_synthesis_pipeline.py", line 46, in __init__
    super().__init__(model=model, **kwargs)
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 94, in __init__
    self.model = self.initiate_single_model(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/models/base/base_model.py", line 144, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(
            ^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/utils/import_utils.py", line 457, in import_module
    importlib.import_module(module_name)
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/models/multi_modal/video_synthesis/text_to_video_synthesis_model.py", line 7, in <module>
    import open_clip
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/open_clip/__init__.py", line 1, in <module>
    from .coca_model import CoCa
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/open_clip/coca_model.py", line 15, in <module>
    from .model import CLIPTextCfg, CLIPVisionCfg, _build_vision_tower, _build_text_tower
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/open_clip/model.py", line 18, in <module>
    from .timm_model import TimmModel
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/open_clip/timm_model.py", line 12, in <module>
    import timm
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/timm/models/maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oem/Documents/gitWorkspace/test/test.py", line 11, in <module>
    pipe = pipeline('text-to-video-synthesis', model_dir.as_posix())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 56, in build_pipeline
    return build_from_cfg(
           ^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/bot/lib/python3.11/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: TextToVideoSynthesisPipeline: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory

```

**Comment by mic2112** [comment]
`
from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys

p = pipeline('text-to-video-synthesis', 'damo/text-to-video-synthesis', device='cpu')
test_text = {
        'text': 'A dog running in the streets',
    }
output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
print('output_video_path:', output_video_path)`

If I specify the device to be CPU, I get a CUDA OOM Error instead

**Comment by johndpope** [comment]
so I did some digging for class GaussianDiffusion(nn.Module): on github - specifically with reference to device

came up with this - (I did attempt to migrate entire class into the codebase - but it's probably going to end up with a different model or something???
but there's this line - that's copying stuff from cpu. 
https://github.com/prophesier/diff-svc/blob/a06ef1edcd4ff451bc3233442795af6be52ec9d4/modules/diff/diffusion.py#LL154


            betas = betas.detach().cpu().numpy() if isinstance(betas, torch.Tensor) else betas

**Comment by mic2112** [comment]
I am trying to run the entire modelscope codebase locally to debug, will reference back here if I make any progress.

**Comment by WangJiuniu** [comment]
This demo requires about 16GB CPU RAM and 16GB GPU RAM. @mic2112

**Comment by WangJiuniu** [comment]
You can try to use Colab like [this page](https://colab.research.google.com/drive/1uW1ZqswkQ9Z9bp5Nbo5z59cAn7I0hE6R?usp=sharing).

**Comment by mic2112** [comment]
So using something like DataParallel isn't possible? @WangJiuniu

**Comment by WangJiuniu** [comment]
The UNet module needs about 16GB GPU memory. So it will be quite complex to run on 12GB GPU. Maybe model parallel would work.

**Comment by ThatCoffeeGuy** [comment]
> See [this page](https://github.com/modelscope/modelscope/blob/master/modelscope/models/multi_modal/video_synthesis/diffusion.py)
> 
> We have fixed this bug by adding "tensor = tensor.to(x.device)", so the "return tensor[t].view(shape).to(x)" is Line 15 now. @ThatCoffeeGuy

thank you, I can confirm that after I made the modifications it started to work for me too. However unfortunately I only have a 12GB GPU and it runs out of memory. 

When I try to run it in CPU mode by `export CUDA_VISIBLE_DEVICES=""`, I can see it starts filling up system ram (I have 64GB of it) but then it crashes with:

`RuntimeError: TextToVideoSynthesisPipeline: TextToVideoSynthesis: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

Could you please tell me if the suggested fix in the error message is going to work and where should I put that line exactly? Thank you.

**Comment by wenmengzhou** [comment]
> > See [this page](https://github.com/modelscope/modelscope/blob/master/modelscope/models/multi_modal/video_synthesis/diffusion.py)
> > We have fixed this bug by adding "tensor = tensor.to(x.device)", so the "return tensor[t].view(shape).to(x)" is Line 15 now. @ThatCoffeeGuy
> 
> thank you, I can confirm that after I made the modifications it started to work for me too. However unfortunately I only have a 12GB GPU and it runs out of memory.
> 
> When I try to run it in CPU mode by `export CUDA_VISIBLE_DEVICES=""`, I can see it starts filling up system ram (I have 64GB of it) but then it crashes with:
> 
> `RuntimeError: TextToVideoSynthesisPipeline: TextToVideoSynthesis: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
> 
> Could you please tell me if the suggested fix in the error message is going to work and where should I put that line exactly? Thank you.

@WangJiuniu  Can you help to look at this problem, can we support text to video run in cpu-only enviroment

**Comment by shiyueGG** [comment]
> > See [this page](https://github.com/modelscope/modelscope/blob/master/modelscope/models/multi_modal/video_synthesis/diffusion.py)
> > We have fixed this bug by adding "tensor = tensor.to(x.device)", so the "return tensor[t].view(shape).to(x)" is Line 15 now. @ThatCoffeeGuy
> 
> thank you, I can confirm that after I made the modifications it started to work for me too. However unfortunately I only have a 12GB GPU and it runs out of memory.
> 
> When I try to run it in CPU mode by `export CUDA_VISIBLE_DEVICES=""`, I can see it starts filling up system ram (I have 64GB of it) but then it crashes with:
> 
> `RuntimeError: TextToVideoSynthesisPipeline: TextToVideoSynthesis: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
> 
> Could you please tell me if the suggested fix in the error message is going to work and where should I put that line exactly? Thank you.

你好 请问你解决了吗。我也遇到了

**Comment by akashbeh** [comment]
我也遇到了
