### ISSUE TITLE
what is the correct version of ModelScope library to use cv_resnet_carddetection_scrfd34gkps

### ISSUE THREAD

**Issue by nemodleo** [modelscope/modelscope#23]
```
$ docker run -it \
> --gpus '"device=all"' \
> --ipc=host --ulimit memlock=-1 --ulimit stack=-1 \
> registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.3.0-py37-torch1.11.0-tf1.15.5-1.0.2

root@a0957b5bb035:/# python
Python 3.7.13 (default, Mar 29 2022, 02:18:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> from modelscope.pipelines import pipeline
2022-11-14 13:25:10,539 - modelscope - INFO - PyTorch version 1.11.0+cu113 Found.
2022-11-14 13:25:10,540 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2022-11-14 13:25:10,540 - modelscope - INFO - No valid ast index found from /mnt/workspace/.cache/modelscope/ast_indexer, rebuilding ast index!
2022-11-14 13:25:10,544 - modelscope - INFO - AST-Scaning the path "/opt/conda/lib/python3.7/site-packages/modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets']

2022-11-14 13:25:24,640 - modelscope - INFO - Scaning done! A number of 425 files indexed! Time consumed 14.096197605133057s
2022-11-14 13:25:24,651 - modelscope - INFO - Loading done! Current index file version is 1.0.2, with md5 9162426873f519b5f40405e5553297ce
>>>
>>> from modelscope.utils.constant import  Tasks
>>> face_detection_34g = pipeline(Tasks.face_detection, 'damo/cv_resnet_carddetection_scrfd34gkps')
2022-11-14 13:25:55,297 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0
2022-11-14 13:25:55,544 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detect.jpg to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmp08luyn2i
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 523k/523k [00:00<00:00, 2.64MB/s]
2022-11-14 13:25:55,940 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detect.jpg in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:55,942 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection1.jpg to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmpxrj3oxt1
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 249k/249k [00:00<00:00, 1.39MB/s]
2022-11-14 13:25:56,329 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection1.jpg in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:56,330 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection2.jpg to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmp794_j45t
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139k/139k [00:00<00:00, 1.10MB/s]
2022-11-14 13:25:56,640 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection2.jpg in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:56,641 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection3.jpg to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmpbom8q4xy
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 75.0k/75.0k [00:00<00:00, 878kB/s]
2022-11-14 13:25:56,909 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/card_detection3.jpg in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:56,909 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=configuration.json to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmp4rh0q8sq
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 138/138 [00:00<00:00, 832kB/s]
2022-11-14 13:25:57,101 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=configuration.json in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:57,101 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=mmcv_scrfd.py to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmpsit250px
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.92k/5.92k [00:00<00:00, 1.06MB/s]
2022-11-14 13:25:57,282 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=mmcv_scrfd.py in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:25:57,283 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=pytorch_model.bin to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmphvs4vg4d
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 76.1M/76.1M [00:13<00:00, 5.91MB/s]
2022-11-14 13:26:10,967 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=pytorch_model.bin in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:26:11,016 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=README.md to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmp4l24x06c
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.96k/5.96k [00:00<00:00, 942kB/s]
2022-11-14 13:26:11,206 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=README.md in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:26:11,206 - modelscope - INFO - downloading http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/traindata.jpg to /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe/tmpfv_3o3mu
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 236k/236k [00:00<00:00, 1.46MB/s]
2022-11-14 13:26:11,548 - modelscope - INFO - storing http://www.modelscope.cn/api/v1/models/damo/cv_resnet_carddetection_scrfd34gkps/repo?Revision=v1.0.0&FilePath=description/traindata.jpg in cache at /mnt/workspace/.cache/modelscope/temp/tmpx2airsoe
2022-11-14 13:26:11,554 - modelscope - WARNING - ('PIPELINES', 'face-detection', 'resnet-card-detection-scrfd34gkps') not found in ast index file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 325, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 243, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    f'{obj_type} is not in the {registry.name}'
KeyError: 'resnet-card-detection-scrfd34gkps is not in the pipelines registry group face-detection. Please make sure the correct version of ModelScope library is used.'
```

**Comment by liuyhwangyh** [comment]
> 

card_detection = pipeline(**_Tasks.card_detection_**, 'damo/cv_resnet_carddetection_scrfd34gkps')
