### ISSUE TITLE
GPT3中文13B参数量文本生成模型 加载失败

### ISSUE THREAD

**Issue by yingwen330** [modelscope/modelscope#283]
>>> done with compiling and loading fused kernels. Compilation time: 9.082 seconds
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/nlp/distributed_gpt3_pipeline.py", line 39, in _instantiate_one
    cls.model = DistributedGPT3(model_dir, rank, **kwargs)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/distributed_gpt3.py", line 980, in __init__
    load_model = pre_load(ckpt_rank, model_dir, tag=path_load_tag)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/nlp/load_checkpoint.py", line 68, in pre_load
    load_path, map_location=lambda storage, loc: storage)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/gpt3/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_13B/model/mp_rank_03_model_states.pt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/nlp/distributed_gpt3_pipeline.py", line 34, in __init__
    super().__init__(model, preprocessor=preprocessor, **kwargs)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/base.py", line 462, in __init__
    **kwargs), ranks)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/gpt3/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_13B/model/mp_rank_03_model_states.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_gpt3_-001.py", line 7, in <module>
    pipe = pipeline(Tasks.text_generation, model=model_id)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: DistributedGPT3Pipeline: [Errno 2] No such file or directory: '/home/gpt3/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_13B/model/mp_rank_03_model_states.pt'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1670433) of binary: /home/gpt3/miniconda3/envs/modelscope/bin/python
Traceback (most recent call last):
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gpt3/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_gpt3_-001.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-22_06:36:55
  host      : test
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1670433)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by wenmengzhou** [comment]
The model weights of gpt3 13B has not been open sourced, If you want to downloat it, you can provide the specific name of your laboratory and the background of the application.  Send an email to [contact@modelscope.cn](mailto:contact@modelscope.cn). We will ask the model contributors to evaluate and then respond to you
