### ISSUE TITLE
No module named 'kantts'

### ISSUE THREAD

**Issue by fuxishuyuan** [modelscope/modelscope#294]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('text-to-speech', 'damo/speech_ptts_autolabel_16k')

`raceback (most recent call last):
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 433, in _get_module
    return importlib.import_module('.' + module_name, self.__name__)
  File "/root/miniconda3/envs/modelscope/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 27, in <module>
    from .voice import Voice
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/models/audio/tts/voice.py", line 13, in <module>
    from kantts.datasets.dataset import get_am_datasets, get_voc_datasets
ModuleNotFoundError: No module named 'kantts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 56, in build_pipeline
    return build_from_cfg(
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 457, in import_module
    importlib.import_module(module_name)
  File "/root/miniconda3/envs/modelscope/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/pipelines/audio/text_to_speech_pipeline.py", line 9, in <module>
    from modelscope.models.audio.tts import SambertHifigan
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 416, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/envs/modelscope/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 435, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import modelscope.models.audio.tts.sambert_hifi because of the following error (look up to see its traceback):
No module named 'kantts'`

**Comment by overfiter** [comment]
I met the same problem, how to solve it?  orz

**Comment by wenmengzhou** [comment]
> I met the same problem, how to solve it? orz

try   pip install kantts -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
