### ISSUE TITLE
使用ChatPLUG报错g++错误Exception: Run cmd failed: "/usr/bin/g++"

### ISSUE THREAD

**Issue by jiweizhangxu** [modelscope/modelscope#305]
环境如下：
![1](https://github.com/modelscope/modelscope/assets/88191580/b4c2d726-bcab-4b9d-a5e2-2081c78c501b)

报错如下：
/root/anaconda3/envs/chatglm/bin/python /usr/local/zx/ChatPLUG-3.7B/add_data_chatplug.py
g++: error: unrecognized command line option ‘-std=c++14’
Traceback (most recent call last):
  File "/usr/local/zx/ChatPLUG-3.7B/add_data_chatplug.py", line 1, in <module>
    from modelscope.pipelines import pipeline
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import LazyImportModule
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/utils/import_utils.py", line 18, in <module>
    from modelscope.utils.ast_utils import (INDEX_KEY, MODULE_KEY, REQUIREMENT_KEY,
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/utils/ast_utils.py", line 25, in <module>
    from modelscope.utils.registry import default_group
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/utils/registry.py", line 11, in <module>
    logger = get_logger()
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/utils/logger.py", line 48, in get_logger
    from modelscope.utils.torch_utils import is_master
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/modelscope/utils/torch_utils.py", line 13, in <module>
    import torch
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/__init__.py", line 4, in <module>
    import jittor as jt
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/g++" "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src/utils/cache_compile.cc" "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src/utils/log.cc" "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src/utils/tracer.cc" "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src/utils/jit_utils.cc" "/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor/src" -I/root/anaconda3/envs/chatglm/include/python3.9 -I/root/anaconda3/envs/chatglm/include/python3.9  -O2   -o "/root/.cache/jittor/jt1.3.7/g++4.8.5/py3.9.16/Linux-3.10.0-1xc5/IntelCoreProcex4a/default/jit_utils_core.cpython-39-x86_64-linux-gnu.so"
[i 0518 14:28:49.382392 40 compiler.py:955] Jittor(1.3.7.13) src: /root/anaconda3/envs/chatglm/lib/python3.9/site-packages/jittor
[i 0518 14:28:49.390292 40 compiler.py:956] g++ at /usr/bin/g++(4.8.5)
[i 0518 14:28:49.390444 40 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++4.8.5/py3.9.16/Linux-3.10.0-1xc5/IntelCoreProcex4a/default
[i 0518 14:28:49.398650 40 __init__.py:411] Found nvcc(10.2.89) at /usr/bin/nvcc.
[i 0518 14:28:49.438185 40 __init__.py:411] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0518 14:28:49.446655 40 __init__.py:411] Found addr2line(2.27) at /usr/bin/addr2line.
[i 0518 14:28:49.603421 40 compiler.py:1010] cuda key:cu10.2.89_sm_37

Process finished with exit code 1

代码如下，就是官方知识增强的示例代码：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.models import Model

model_id = 'damo/ChatPLUG-3.7B'
pipeline_ins = pipeline(Tasks.fid_dialogue, model=model_id,model_revision='v1.0.1')

# 数据预处理设置
preprocess_params = {
    'max_encoder_length': 380, # encoder最长输入长度
    'context_turn': 5 # context最长轮数
}

# 解码策略，默认为beamsearch
forward_params = {
    'min_length': 10,
    'max_length': 512,
    'num_beams': 3,
    'temperature': 0.8,
    'do_sample': False,
    'early_stopping': True,
    'top_k': 50,
    'top_p': 0.8,
    'repetition_penalty': 1.2,
    'length_penalty': 1.2,
    'no_repeat_ngram_size': 6
}
kwargs = {
    'preprocess_params': preprocess_params,
    'forward_params': forward_params
}

# 支持输入多段外部知识文本，进行知识增强
know_list = [
    "《狂飙》由徐纪周执导的。《狂飙》的导演徐纪周也是编剧之一，代表作品有《永不磨灭的番号》《特战荣耀》《心理罪之城市之光》《杀虎口》《胭脂》等",
    "《狂飙》（The Knockout）是一部由 张译、张颂文、李一桐、张志坚 领衔主演，韩童生 特邀主演，吴健、郝平 友情出演，高叶、贾冰、李健 主演，徐纪周 执导，朱俊懿、徐纪周 担任总编剧的 刑侦",
    "狂飙是由中央政法委宣传教育局，中央政法委政法信息中心指导，爱奇艺，留白影视出品，徐纪周执导，张译，李一桐，张志坚领衔主演的刑侦剧。不是。是徐纪周，1976年12月19日出生，毕业于中央戏剧",
]

input = {
    "history": "你好[SEP]你好!很高兴与你交流![SEP]狂飙的导演是谁呀",
    "bot_profile": "我是达摩院的语言模型ChatPLUG， 是基于海量数据训练得到。",
    # 推理时，会根据[SEP]符号拆分为多段文本，分别和context合并后输入模型中，以节省计算量
    "knowledge": "[SEP]".join(know_list),
}

result = pipeline_ins(input,**kwargs)
print(result)

**Comment by NaturalSelect** [comment]
```log
g++: error: unrecognized command line option ‘-std=c++14’
```

The reason seems to be that the version of GCC is too old. 

Please ensure that the version is at least 5 to support cpp 2014 standard.

See also:[compiler support](https://en.cppreference.com/w/cpp/compiler_support/14)
