### ISSUE TITLE
模型下载下来后，怎么在本地用起来？

### ISSUE THREAD

**Issue by 631068264** [modelscope/modelscope#31]
这个里面只是 交代了模型的下载 https://modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD

而我看模型的加载例子只有类似这种, 搞个model id load进去  ， 没有说怎么在本地使用的例子

```py
from modelscope.pipelines import pipeline
pipeline_ins = pipeline('fill-mask', model='damo/nlp_structbert_fill-mask_english-large')
input = 'Everything in [MASK] you call reality is really [MASK] a reflection of your [MASK].'
print(pipeline_ins(input))

```

**Comment by yingdachen** [comment]
model id load进去后，就会自动触发模型下载到本地，并且被使用了。

如果手动下载模型到本地，那提供model=‘path/to/local/dir’ 参数就可以。

**Comment by v-yunbin** [comment]
> model id load进去后，就会自动触发模型下载到本地，并且被使用了。
> 
> 如果手动下载模型到本地，那提供model=‘path/to/local/dir’ 参数就可以。

模型下载到了本地，报错
```
2023-02-16 18:14:11,344 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-02-16 18:14:11,346 - modelscope - INFO - Loading ast index from /home/ybZhang/.cache/modelscope/ast_indexer
2023-02-16 18:14:11,432 - modelscope - INFO - Loading done! Current index file version is 1.3.0, with md5 8ab658ed40d85d1d6764da5171113ba7 and a total number of 746 components indexed
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/util.py", line 35, in is_official_hub_impl
    _ = HubApi().get_model(path, revision=revision)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/hub/api.py", line 222, in get_model
    if is_ok(r.json()):
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_tts.py", line 9, in <module>
    sambert_hifigan_tts =pipeline(
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 101, in pipeline
    model = normalize_model_input(model, model_revision)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 23, in normalize_model_input
    if isinstance(model, str) and is_official_hub_path(model, model_revision):
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/util.py", line 41, in is_official_hub_path
    return is_official_hub_impl(path)
  File "/home/ybZhang/miniconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/util.py", line 38, in is_official_hub_impl
    raise ValueError(f'invalid model repo path {e}')
ValueError: invalid model repo path Expecting value: line 1 column 1 (char 0)
```
