### ISSUE TITLE
SambertHifigan个性化语音合成-中文-预训练-16k 问题

### ISSUE THREAD

**Issue by xiabo2011** [modelscope/modelscope#314]
**General Question**

```python
from modelscope.metainfo import Trainers
from modelscope.trainers import build_trainer
from modelscope.utils.audio.audio_utils import TtsTrainType

pretrained_model_id = 'damo/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k'

dataset_id = "./output_training_data/"
pretrain_work_dir = "./pretrain_work_dir/"
        
train_info = {
    TtsTrainType.TRAIN_TYPE_SAMBERT: {  
        'train_steps': 202,              
        'save_interval_steps': 200,      
        'log_interval': 10             
    }
}

kwargs = dict(
    model=pretrained_model_id,               
    model_revision = "v1.0.5",
    work_dir=pretrain_work_dir,              
    train_dataset=dataset_id,                
    train_type=train_info                  
)

trainer = build_trainer(Trainers.speech_kantts_trainer,
                        default_args=kwargs)

trainer.train()
```
运行上面代码报错，报错信息如下：
`onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ./pretrain_work_dir/orig_model/basemodel_16k/speaker_embedding/se.onnx failed:Load model ./pretrain_work_dir/orig_model/basemodel_16k/speaker_embedding/se.onnx failed. File doesn't exist`
目录下确实没有se.onnx，但是有se.model，另外运行日志前面会报错”Load pinyin_en_mix_dict failed“。
请问这两个问题该如何解决呢？感谢

**Comment by xiabo2011** [comment]
补充一些信息：上面代码来自https://modelscope.cn/models/damo/speech_personal_sambert-hifigan_nsf_tts_zh-cn_pretrain_16k/summary
安装是按照https://modelscope.cn/docs/%E7%8E%AF%E5%A2%83%E5%AE%89%E8%A3%85
源码安装也是同样的报错

**Comment by xiabo2011** [comment]
你好，看到咱们升级了模型v1.0.5到v1.0.6，增加了一个se.onnx文件，但是文件大小跟se.model一样，怀疑是否格式上存在问题呢，目前报Probuf解析的错误，具体错误内容如下：
```
Traceback (most recent call last):
  File "fine_tune.py", line 33, in <module>
    trainer.train()
  File "/home/user/modelscope-master/modelscope/trainers/audio/tts_trainer.py", line 229, in train
    self.prepare_data()
  File "/home/user/modelscope-master/modelscope/trainers/audio/tts_trainer.py", line 208, in prepare_data
    se_model)
  File "/home/user/modelscope-master/modelscope/preprocessors/tts.py", line 37, in __call__
    speaker_name, target_lang, skip_script, se_model)
  File "/home/user/modelscope-master/modelscope/preprocessors/tts.py", line 57, in do_data_process
    targetLang, skip_script, se_model)
  File "/home/anaconda3/envs/modelscope/lib/python3.7/site-packages/kantts/preprocess/data_process.py", line 200, in process_data
    se_model,
  File "/home/anaconda3/envs/modelscope/lib/python3.7/site-packages/kantts/preprocess/se_processor/se_processor.py", line 67, in process
    sess = onnxruntime.InferenceSession(se_onnx, sess_options=opts)
  File "/home/anaconda3/envs/modelscope/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/anaconda3/envs/modelscope/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrain_work_dir/orig_model/basemodel_16k/speaker_embedding/se.onnx failed:Protobuf parsing failed.
```
