### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

### ISSUE THREAD

**Issue by onefish51** [modelscope/modelscope#323]
在测试`https://modelscope.cn/models/damo/cv_unet_person-image-cartoon-sd-illustration_compound-models`模型的时候出现报错
```sh
Traceback (most recent call last):
  File "run_sdk.py", line 72, in <module>
    p = pipeline('image-portrait-stylization', 'damo/cv_unet_person-image-cartoon-sd-illustration_compound-models')
  File "/opt/conda/envs/dctnet/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 141, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/opt/conda/envs/dctnet/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 55, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/opt/conda/envs/dctnet/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
google.protobuf.message.DecodeError: ImageCartoonPipeline: Error parsing message with type 'tensorflow.GraphDef'
```
环境配置按照DCT-Net GitHub中配置的：
```sh
conda create -n dctnet python=3.7
conda activate dctnet
pip install --upgrade tensorflow-gpu==1.15 # GPU support, use tensorflow for CPU only
pip install "modelscope[cv]==1.3.2" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
pip install "modelscope[multi-modal]==1.3.2" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
```
测试脚本按照 [quickstart](https://modelscope.cn/models/damo/cv_unet_person-image-cartoon-sd-illustration_compound-models/quickstart)和 [run_sdk.py](https://github.com/menyifang/DCT-Net/blob/main/run_sdk.py) 写的：
```Python
import cv2
from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

##### DCT-Net
## anime style
img_cartoon = pipeline(Tasks.image_portrait_stylization, 
                       model='damo/cv_unet_person-image-cartoon_compound-models')
result = img_cartoon('input.png')
cv2.imwrite('result_anime.png', result[OutputKeys.OUTPUT_IMG])

#### DCT-Net + SD
## design style
img_cartoon = pipeline(Tasks.image_portrait_stylization,
                       model='damo/cv_unet_person-image-cartoon-sd-design_compound-models')
result = img_cartoon('input.png')
cv2.imwrite('result_sd_design.png', result[OutputKeys.OUTPUT_IMG])
```
其中前一个`cartoon`风格是可以正常运行的，但是`DCT-Net + SD 的 design`会出现上面的报错。
前一个模型文件是通过 [使用Library Hub下载模型](https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD)的方式下载的，后一个模型是通过[使用Git下载模型](https://www.modelscope.cn/docs/%E6%A8%A1%E5%9E%8B%E7%9A%84%E4%B8%8B%E8%BD%BD)的方法下载的（为什么不用同样的方法，是因为按照前面的方法下载会报错）

**Comment by onefish51** [comment]
又测了一下，发现是Git下载的模型的问题，换成`snapshot_download`下载的模型就好了，晕死

**Comment by shiguangliuguo** [comment]
> 又测了一下，发现是Git下载的模型的问题，换成`snapshot_download`下载的模型就好了，晕死

妙啊
