### ISSUE TITLE
加载模型报错 damo/nlp_gpt3_text-generation_1.3B

### ISSUE THREAD

**Issue by xsxs89757** [modelscope/modelscope#326]
```python 
from modelscope.models import Model
model = Model.from_pretrained('damo/nlp_gpt3_text-generation_1.3B')
```
```
2023-06-08 15:38:32,058 - modelscope - INFO - PyTorch version 1.13.1 Found.
2023-06-08 15:38:32,059 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-06-08 15:38:32,091 - modelscope - INFO - Loading done! Current index file version is 1.6.0, with md5 e9de69f8d99c9828c57b79e5ef10339f and a total number of 848 components indexed
2023-06-08 15:38:32,492 - modelscope - INFO - Model revision not specified, use the latest revision: v1.3.0
2023-06-08 15:38:32,771 - modelscope - INFO - initialize model from /root/.cache/modelscope/hub/damo/nlp_gpt3_text-generation_1.3B
Traceback (most recent call last):
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 66, in _instantiate
    return cls(**kwargs)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/nlp/gpt3/text_generation.py", line 34, in __init__
    self.model = DistributedGPT3(model_dir, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2.py", line 3, in <module>
    model = Model.from_pretrained('damo/nlp_gpt3_text-generation_1.3B')
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 144, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/models/builder.py", line 36, in build_model
    cfg, MODELS, group_key=task_name, default_args=default_args)
  File "/root/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GPT3ForTextGeneration: __init__() missing 1 required positional argument: 'rank'
```

**Comment by Firmament-cyou** [comment]
If you want to use the GPT-3 model for inference, it is recommended to use pipeline. An example is as follows:
```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    input = '实例输入'
    model_id = 'damo/nlp_gpt3_text-generation_1.3B'
    pipe = pipeline(Tasks.text_generation, model=model_id)
    print(pipe(input, max_length=512))
```

Since the model of size 1.3B and above supports distributed training and inference methods, the `Model` needs the identification of the corresponding process when initializing the model, that is, the `rank` parameter.

If you know that you need to initialize each model independently on multiple processes, you can enter the rank parameter in the code, for example:
> process 1
`model = Model.from_pretrained('damo/nlp_gpt3_text-generation_1.3B', rank=0)`

> process 2
`model = Model.from_pretrained('damo/nlp_gpt3_text-generation_1.3B', rank=1)`

At this point, you need to use multi-process startup methods such as `torchrun` to ensure communication and synchronization between processes.
