### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by keeepman** [modelscope/modelscope#334]
环境：windows11 python3.10  
按照要求安装了环境，pip install "modelscope[nlp]" -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html和pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118，运行报错Distributed package doesn't have NCCL built in,查询资料发现windows系统不支持NCCL 需要改为gloo，请问是在代码的哪一处改？或者有其他解决方法？

**Comment by keeepman** [comment]
code:
```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
import os

if __name__ == '__main__':
    os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"
    input = '程序员脱发用什么洗发水'
    model_id = 'damo/nlp_gpt3_text-generation_2.7B'
    pipe = pipeline(Tasks.text_generation, model=model_id)

    print(pipe(input, max_length=512))
```
log:
```log
2023-06-20 21:10:48,866 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-06-20 21:10:48,867 - modelscope - INFO - TensorFlow version 2.12.0 Found.
2023-06-20 21:10:48,867 - modelscope - INFO - Loading ast index from C:\Users\69048\.cache\modelscope\ast_indexer
2023-06-20 21:10:48,912 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 9be2c5e65a02c287ccff03cfaafaca96 and a total number of 849 components indexed
2023-06-20 21:10:50,106 - modelscope - INFO - Model revision not specified, use the latest revision: v1.2.0
2023-06-20 21:10:52,063 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-06-20 21:10:52,064 - modelscope - INFO - TensorFlow version 2.12.0 Found.
2023-06-20 21:10:52,065 - modelscope - INFO - Loading ast index from C:\Users\69048\.cache\modelscope\ast_indexer
2023-06-20 21:10:52,110 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 9be2c5e65a02c287ccff03cfaafaca96 and a total number of 849 components indexed
using world size: 1, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 1 
using torch.float32 for parameters ...
> initializing torch distributed ...
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - �����������У�������ĵ�ַ��Ч��).
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\MyTool\python\python3.10.11\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\MyTool\python\python3.10.11\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\pipelines\nlp\distributed_gpt3_pipeline.py", line 39, in _instantiate_one
    cls.model = DistributedGPT3(model_dir, rank, **kwargs)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\models\nlp\gpt3\distributed_gpt3.py", line 958, in __init__
    init_megatron_util(megatron_cfg, model_dir, rank=rank)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\utils\megatron_utils.py", line 64, in init_megatron_util
    initialize_megatron(megatron_cfg)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\megatron_util\initialize.py", line 70, in initialize_megatron
    finish_mpu_init()
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\megatron_util\initialize.py", line 51, in finish_mpu_init
    _initialize_distributed(master_ip, master_port)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\megatron_util\initialize.py", line 139, in _initialize_distributed
    torch.distributed.init_process_group(
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\pipelines\nlp\distributed_gpt3_pipeline.py", line 34, in __init__
    super().__init__(model, preprocessor=preprocessor, **kwargs)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\pipelines\base.py", line 466, in __init__
    self.model_pool.map(
  File "C:\MyTool\python\python3.10.11\lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\MyTool\python\python3.10.11\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
RuntimeError: Distributed package doesn't have NCCL built in

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MyTool\pycharm\PythonProject\modelTest\main.py", line 9, in <module>
    pipe = pipeline(Tasks.text_generation, model=model_id)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\pipelines\builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\pipelines\builder.py", line 56, in build_pipeline
    return build_from_cfg(
  File "C:\MyTool\pycharm\PythonProject\modelTest\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
RuntimeError: DistributedGPT3Pipeline: Distributed package doesn't have NCCL built in
```

**Comment by keeepman** [comment]
Any suggestions?

**Comment by wenmengzhou** [comment]
can you use wsl  in Windows to run the code in linux env, we haven't tested distributed function on Windows
