### ISSUE TITLE
OCR的场景识别模型推理遇到：missing 2 required positional arguments: 'op' and 'message'

### ISSUE THREAD

**Issue by lipeng1109** [modelscope/modelscope#342]
问题：OCR的场景识别模型推理遇到：missing 2 required positional arguments: 'op' and 'message'
Traceback (most recent call last):
  File "end_to_end_pipeline.py", line 178, in <module>
    ocr_detection = pipeline(Tasks.ocr_detection, model=det_model)
  File "/home/peng.li/.conda/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 140, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/peng.li/.conda/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 57, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/home/peng.li/.conda/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: __init__() missing 2 required positional arguments: 'op' and 'message'

使用安装包：modelscope=1.4.0、1.5.0都会出现这个错误，使用1.3.0不会

**Comment by lipeng1109** [comment]
使用modelscope=1.4.0遇到上述错误
