### ISSUE TITLE
When I want to export hand-static model as onnx

### ISSUE THREAD

**Issue by yiyexy** [modelscope/modelscope#36]
model_id = 'damo/cv_mobileface_hand-static'
model = Model.from_pretrained(model_id)
output_files = Exporter.from_model(model).export_onnx(shape=(1, 310,310,3), opset=13, output_dir='/tmp')
print(output_files)

Traceback (most recent call last):
  File "/home/luolab/yin/modelscope/test_modelscope.py", line 15, in <module>
    output_files = Exporter.from_model(model).export_onnx(shape=(1, 310,310,3), opset=13, output_dir='/tmp')
  File "/home/luolab/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/exporters/base.py", line 39, in from_model
    exporter = build_exporter(export_cfg, task_name, kwargs)
  File "/home/luolab/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/exporters/builder.py", line 20, in build_exporter
    return build_from_cfg(
  File "/home/luolab/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/utils/registry.py", line 197, in build_from_cfg
    raise KeyError(
KeyError: 'hand-static is not in the exporters registry group hand-static. Please make sure the correct version of ModelScope library is used.'

**Comment by yingdachen** [comment]
this particular model is only integrated into pipeline, without specific model abstraction. you may use the pipeline with the folllowing sample code (as shown in the model card)

`from modelscope.outputs import OutputKeys
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

hand_static = pipeline(Tasks.hand_static, model='damo/cv_mobileface_hand-static')
result_status = hand_static({'img_path': 'data/test/images/hand_static.jpg'})
result = result_status[OutputKeys.OUTPUT]`

**Comment by yiyexy** [comment]
> model

Thx，I had use it with pipeline. But I want to use it in embedded sys. Maybe it is not a right time. Thx again!
