### ISSUE TITLE
modelscope can't correctly load the csv in the datasets

### ISSUE THREAD

**Issue by SWHL** [modelscope/modelscope#370]
Thanks for your error report and we appreciate it a lot.

**Checklist**

- [x] I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
- [x] I have searched related issues but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**
- I upload a custom dataset, named table-recognition. When I load it by the modelscope package, I meet the following error:
  ```bash
  (py38) [xxxx@gpu01 table-recognition-metric]$ python test_datasets.py 
  2023-07-10 10:38:47,083 - modelscope - INFO - Loading ast index from /home/xxxx/.cache/modelscope/ast_indexer
  2023-07-10 10:38:47,128 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 6eb865a11602e241b44e7d812ba21329 and a total number of 861 components indexed
  2023-07-10 10:38:48,343 - modelscope - WARNING - Reusing dataset table_recognition (./datasets/liekkas/table_recognition/master/data_files)
  2023-07-10 10:38:48,343 - modelscope - INFO - Generating dataset table_recognition (./datasets/liekkas/table_recognition/master/data_files)
  2023-07-10 10:38:48,343 - modelscope - INFO - Reusing cached meta-data file: ./datasets/liekkas/table_recognition/master/data_files/e8fcf6d05822205d569e85e4d506343e
  Downloading data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s]
  Extracting data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 651.69it/s]
  Traceback (most recent call last):
    File "test_datasets.py", line 7, in <module>
      ms_test_dataset = MsDataset.load(
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/ms_dataset.py", line 284, in load
      dataset_inst = remote_dataloader_manager.load_dataset(
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
      oss_downloader.process()
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 83, in process
      self._prepare_and_download()
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 147, in _prepare_and_download
      self.dataset = self.data_files_manager.fetch_data_files(
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/data_files/data_files_manager.py", line 116, in fetch_data_files
      return builder.as_dataset()
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/download/dataset_builder.py", line 237, in as_dataset
      return DatasetDict({
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/download/dataset_builder.py", line 238, in <dictcomp>
      k: self._convert_csv_to_dataset(k, v)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/modelscope/msdatasets/download/dataset_builder.py", line 218, in _convert_csv_to_dataset
      df = pd.read_csv(
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/streaming.py", line 71, in wrapper
      return function(*args, use_auth_token=use_auth_token, **kwargs)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/datasets/download/streaming_download_manager.py", line 804, in xpandas_read_csv
      return pd.read_csv(xopen(filepath_or_buffer, "rb", use_auth_token=use_auth_token), **kwargs)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
      return func(*args, **kwargs)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 488, in _read
      return parser.read(nrows)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1047, in read
      index, columns, col_dict = self._engine.read(nrows)
    File "/da2/miniconda3/envs/py38/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
      chunks = self._reader.read_low_memory(nrows)
    File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
    File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
    File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
    File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
  pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 7, saw 3
  ```

**To Reproduce**
* What command or script did you run?
  ```python
  from modelscope.msdatasets import MsDataset
  
  ms_test_dataset = MsDataset.load(
      'table_recognition', namespace='liekkas', subset_name='default', split='test',
      cache_dir='./datasets'
  )
  print(next(iter(ms_test_dataset)))
  ```
* Did you make any modifications on the code or config? Did you understand what you have modified?
  * No
* What dataset did you use?
  * [liekkas/table_recognition](https://www.modelscope.cn/datasets/liekkas/table_recognition/summary)

**Your Environments (__required__)**
* OS: `Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz`
- modelscope: `1.7.1`
- python: `3.8`
 
**Attachment file**:
[test_table_recognition.csv](https://github.com/modelscope/modelscope/files/12001018/test_table_recognition.csv)

⚠️Notion： I change the csv to json format to store the meta, now the error disappeared.

**Comment by SWHL** [comment]
The question has been solved in the Ding group. 
Suggest: use the csv format, not the jsonl.
