### ISSUE TITLE
Asr 推理问题

### ISSUE THREAD

**Issue by Stonexiao** [modelscope/modelscope#425]
OS: [e.g. linux]
Python/C++ Version：3.7.16
Package Version：pytorch=1.11.0、torchaudio=0.11.0、modelscope=1.7.1、funasr=0.7.1
Model：speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：
Details：asr转写
Error log：
Traceback (most recent call last):
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 163, in __init__
    **kwargs,
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/funasr/bin/asr_inference_launch.py", line 1632, in inference_launch
    return inference_paraformer_vad_punc(**kwargs)
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/funasr/bin/asr_inference_launch.py", line 520, in inference_paraformer_vad_punc
    speech2vadsegment = Speech2VadSegment(**speech2vadsegment_kwargs)
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/funasr/bin/vad_infer.py", line 47, in __init__
    vad_infer_config, vad_model_file, None, device, task_name="vad"
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/funasr/build_utils/build_model_from_file.py", line 76, in build_model_from_file
    model.encoder.load_state_dict(model_dict)
  File "/home/xiaoguo/.conda/envs/modelscope/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FSMN:
	While copying the parameter named "fsmn.0.fsmn_block.conv_left.weight", whose dimensions in the model are torch.Size([128, 1, 20, 1]) and whose dimensions in the checkpoint are torch.Size([128, 1, 20, 1]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.',).
	While copying the parameter named "fsmn.1.fsmn_block.conv_left.weight", whose dimensions in the model are torch.Size([128, 1, 20, 1]) and whose dimensions in the checkpoint are torch.Size([128, 1, 20, 1]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.',).
	While copying the parameter named "fsmn.2.fsmn_block.conv_left.weight", whose dimensions in the model are torch.Size([128, 1, 20, 1]) and whose dimensions in the checkpoint are torch.Size([128, 1, 20, 1]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.',).
	While copying the parameter named "fsmn.3.fsmn_block.conv_left.weight", whose dimensions in the model are torch.Size([128, 1, 20, 1]) and whose dimensions in the checkpoint are torch.Size([128, 1, 20, 1]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.',).

**Comment by wenmengzhou** [comment]
@langgz please help to look at this issue

**Comment by langgz** [comment]
The error does matters with funasr. Please ref to [issue](https://forums.developer.nvidia.com/t/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-device/182914)
