### ISSUE TITLE
使用python pipeline推理，下载模型一直中断。

### ISSUE THREAD

**Issue by rookie0607** [modelscope/modelscope#434]
OS: linuxPython/C++ Version：3.7.16Package Version：pytorch1.11.0、torchaudio0.11.0、modelscope1.7.1、funasr 0.7.1Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorchCommand：./infer.shDetails：使用python pipeline推理，下载模型一直中断。Error log：
Decoding ...
2023-08-01 19:15:24,487 - modelscope - INFO - PyTorch version 1.11.0 Found.
2023-08-01 19:15:24,488 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-08-01 19:15:24,521 - modelscope - INFO - Loading done! Current index file version is 1.7.1, with md5 8ca495b3c080c13c8becff7b0014b173 and a total number of 861 components indexed
2023-08-01 19:15:25,372 - modelscope - INFO - Model revision not specified, use the latest revision: v1.2.4
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 1.24MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 408k/408k [00:00<00:00, 936kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 55.5k/55.5k [00:00<00:00, 1.69MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 790/790 [00:00<00:00, 251kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 91.0/91.0 [00:00<00:00, 30.3kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 229kB/s]
Downloading:  18%|██████████████████▊                                                                                   | 158M/859M [01:22<04:54, 2.49MB/s]Traceback (most recent call last):
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/miniconda3/envs/funasr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/miniconda3/envs/funasr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 27, in <module>
    modelscope_infer(args)
  File "infer.py", line 9, in modelscope_infer
    inference_pipeline = pipeline(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 106, in pipeline
    model = normalize_model_input(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 33, in normalize_model_input
    model = snapshot_download(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 140, in snapshot_download
    parallel_download(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 243, in parallel_download
    list(executor.map(download_part, tasks))
  File "/opt/miniconda3/envs/funasr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/miniconda3/envs/funasr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/miniconda3/envs/funasr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 197, in download_part
    r = requests.get(
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/miniconda3/envs/funasr/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Downloading:  18%|██████████████████▊                                                                                   | 158M/859M [01:22<06:04, 2.02MB/s]

**Comment by Maxhyl** [comment]
我也遇到这个问题，下载都3、40就中断然后又要重新下载，请问这个问题有解决吗？

**Comment by team79** [comment]
@Maxhyl @rookie0607 请问你们是在哪个区域下载呀？

**Comment by rookie0607** [comment]
> @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？

ASR

**Comment by rookie0607** [comment]
> @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
modelscope 1.6.1可以正常下载，1.7.1及以上会异常中断

**Comment by team79** [comment]
> > @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
> 
> ASR

请问你下载时网络所在的国家和地区是哪里呀？我们排查下是否是网络问题。

**Comment by Maxhyl** [comment]
> > > @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
> > 
> > 
> > ASR
> 
> 请问你下载时网络所在的国家和地区是哪里呀？我们排查下是否是网络问题。

深圳，在服务器下载一直中断，用的是1.8.1的版本，后面没办法就本地下载再传到服务器

**Comment by yingdachen** [comment]
服务器是哪里的服务器呢

**Comment by Maxhyl** [comment]
> 服务器是哪里的服务器呢

广州

**Comment by team79** [comment]
> 一直

麻烦看看在您的服务器上设置 MODELSCOPE_DOWNLOAD_PARALLELS 这个环境变量为 1 来关闭并行下载看看能否暂时规避这个问题，如果确认是这个问题，我们在后续版本优化下

**Comment by team79** [comment]
> > > > @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
> > > 
> > > 
> > > ASR
> > 
> > 
> > 请问你下载时网络所在的国家和地区是哪里呀？我们排查下是否是网络问题。
> 
> 深圳，在服务器下载一直中断，用的是1.8.1的版本，后面没办法就本地下载再传到服务器



麻烦看看在您的服务器上设置 MODELSCOPE_DOWNLOAD_PARALLELS 这个环境变量为 1 来关闭并行下载看看能否暂时规避这个问题，如果确认是这个问题，我们在后续版本优化下

**Comment by liuyhwangyh** [comment]
> 
重试可以下载完整吗？是某一个文件一直有问题还是大文件有的下载成功，部分会遇到这个问题，重试也可以下载？

**Comment by Maxhyl** [comment]
> > > > > @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
> > > > 
> > > > 
> > > > ASR
> > > 
> > > 
> > > 请问你下载时网络所在的国家和地区是哪里呀？我们排查下是否是网络问题。
> > 
> > 
> > 深圳，在服务器下载一直中断，用的是1.8.1的版本，后面没办法就本地下载再传到服务器
> 
> 麻烦看看在您的服务器上设置 MODELSCOPE_DOWNLOAD_PARALLELS 这个环境变量为 1 来关闭并行下载看看能否暂时规避这个问题，如果确认是这个问题，我们在后续版本优化下

一样不行。
>>> from modelscope.utils.constant import Tasks
>>> model_id = 'qwen/Qwen-7B-Chat'
>>> pipe = pipeline(
...             task=Tasks.chat, model=model_id, device_map='auto')
2023-08-10 14:15:16,525 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0

Downloading:  40%|██████████████████████████████▉                                              | 5.78G/14.4G [2:23:12<3:37:11, 709kB/s]


Downloading:  51%|███████████████████████████████████████                                      | 7.30G/14.4G [3:00:46<2:55:24, 723kB/s]
2023-08-10 17:16:04,529 - modelscope - ERROR - File pytorch_model.bin download incomplete, content_length: 15442733145 but the                     file downloaded length: 7837581457, please download again
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 106, in pipeline
    model = normalize_model_input(
  File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 33, in normalize_model_input
    model = snapshot_download(
  File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 149, in snapshot_download
    http_get_file(
  File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/hub/file_download.py", line 327, in http_get_file
    raise FileDownloadError(msg)
modelscope.hub.errors.FileDownloadError: File pytorch_model.bin download incomplete, content_length: 15442733145 but the                     file downloaded length: 7837581457, please download again

**Comment by rookie0607** [comment]
> MODELSCOPE_DOWNLOAD_PARALLELS

北京

**Comment by 66li** [comment]
我也是类似的问题，是下载到本地的磁盘文件系统吗，
还是挂载的远程文件系统

**Comment by ae86sen** [comment]
还是没有解决吗？一直中断。。

**Comment by team79** [comment]
> > > > > > @Maxhyl @rookie0607 请问你们是在哪个区域下载呀？
> > > > > 
> > > > > 
> > > > > ASR
> > > > 
> > > > 
> > > > 请问你下载时网络所在的国家和地区是哪里呀？我们排查下是否是网络问题。
> > > 
> > > 
> > > 深圳，在服务器下载一直中断，用的是1.8.1的版本，后面没办法就本地下载再传到服务器
> > 
> > 
> > 麻烦看看在您的服务器上设置 MODELSCOPE_DOWNLOAD_PARALLELS 这个环境变量为 1 来关闭并行下载看看能否暂时规避这个问题，如果确认是这个问题，我们在后续版本优化下
> 
> 一样不行。
> 
> > > > from modelscope.utils.constant import Tasks
> > > > model_id = 'qwen/Qwen-7B-Chat'
> > > > pipe = pipeline(
> > > > ...             task=Tasks.chat, model=model_id, device_map='auto')
> > > > 2023-08-10 14:15:16,525 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0
> 
> Downloading: 40%|██████████████████████████████▉ | 5.78G/14.4G [2:23:12<3:37:11, 709kB/s]
> 
> Downloading: 51%|███████████████████████████████████████ | 7.30G/14.4G [3:00:46<2:55:24, 723kB/s] 2023-08-10 17:16:04,529 - modelscope - ERROR - File pytorch_model.bin download incomplete, content_length: 15442733145 but the file downloaded length: 7837581457, please download again Traceback (most recent call last): File "", line 1, in File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 106, in pipeline model = normalize_model_input( File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 33, in normalize_model_input model = snapshot_download( File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/hub/snapshot_download.py", line 149, in snapshot_download http_get_file( File "/home/edcuser/.local/lib/python3.10/site-packages/modelscope/hub/file_download.py", line 327, in http_get_file raise FileDownloadError(msg) modelscope.hub.errors.FileDownloadError: File pytorch_model.bin download incomplete, content_length: 15442733145 but the file downloaded length: 7837581457, please download again

可以找个网速快点的地方试试么，我看下载速度只有几百k，因为文件比较大，如果网络质量太差是可能失败
