### ISSUE TITLE
_batch_encode_plus() got an unexpected keyword argument 'label2id'

### ISSUE THREAD

**Issue by 1034662268** [modelscope/modelscope#442]
/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/bin/python /Users/edy/PycharmProjects/pythonProject2/test_structbert.py 
2023-08-07 09:45:45,874 - modelscope - INFO - PyTorch version 1.11.0 Found.
2023-08-07 09:45:45,876 - modelscope - INFO - Loading ast index from /Users/edy/.cache/modelscope/ast_indexer
2023-08-07 09:45:45,914 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 dfe0c44a1cbd1117ff92d95368f3a1fd and a total number of 849 components indexed
2023-08-07 09:45:47,016 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0
2023-08-07 09:45:47,416 - modelscope - INFO - initiate model from /Users/edy/.cache/modelscope/hub/damo/nlp_structbert_alimeeting_action-classification_chinese-base
2023-08-07 09:45:47,416 - modelscope - INFO - initiate model from location /Users/edy/.cache/modelscope/hub/damo/nlp_structbert_alimeeting_action-classification_chinese-base.
2023-08-07 09:45:47,418 - modelscope - INFO - initialize model from /Users/edy/.cache/modelscope/hub/damo/nlp_structbert_alimeeting_action-classification_chinese-base
2023-08-07 09:45:51,144 - modelscope - INFO - cuda is not available, using cpu instead.
Traceback (most recent call last):
  File "/Users/edy/PycharmProjects/pythonProject2/test_structbert.py", line 6, in <module>
    output = text_classification("今天会议的第一个结论是明天先收集用户的需求吗？")
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 212, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 240, in _process_single
    out = self.preprocess(input, **preprocess_params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 381, in preprocess
    return self.preprocessor(inputs, **preprocess_params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/preprocessors/nlp/fill_mask_preprocessor.py", line 54, in __call__
    output = self._tokenize_text(text_a, text_b, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/preprocessors/nlp/fill_mask_preprocessor.py", line 144, in _tokenize_text
    return self.nlp_tokenizer(sequence1, sequence2, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/modelscope/preprocessors/nlp/transformers_tokenizer.py", line 108, in __call__
    return self.tokenizer(text, text_pair, **tokenize_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2577, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2683, in _call_one
    return self.encode_plus(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2756, in encode_plus
    return self._encode_plus(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/modelscope/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 497, in _encode_plus
    batched_output = self._batch_encode_plus(
TypeError: _batch_encode_plus() got an unexpected keyword argument 'label2id'

求救

**Comment by lqzzy** [comment]
我也遇到了相同的问题，请问呢你解决了吗
