### ISSUE TITLE
TypeError: VideoCaptioningPipeline: HiTeAForAllTasks: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Xiyu-AI** [modelscope/modelscope#450]
您好，在进行视频字幕生成的时候出现的问题。
推理代码：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

model_id = 'damo/multi-modal_hitea_video-captioning_base_en'
input_caption = 'http://xke-repo.oss-cn-hangzhou.aliyuncs.com/models/release/vid_hitea_videocap.avi'

pipeline_caption = pipeline(Tasks.video_captioning, model=model_id)
result = pipeline_caption(input_caption)
print(result)

但是报错如下：
Traceback (most recent call last):
  File "/home/xzy/xzy/modelscope/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/home/xzy/xzy/modelscope/modelscope/models/base/base_model.py", line 66, in _instantiate
    return cls(**kwargs)
  File "/home/xzy/xzy/modelscope/modelscope/models/multi_modal/mplug_for_all_tasks.py", line 99, in __init__
    self.model = HiTeA.from_pretrained(model_dir)
  File "/home/xzy/xzy/modelscope/modelscope/models/multi_modal/mplug/modeling_mplug.py", line 2520, in from_pretrained
    model = task_mapping[config.task](config)
  File "/home/xzy/xzy/modelscope/modelscope/models/multi_modal/mplug/modeling_mplug.py", line 2744, in __init__
    super().__init__(config)
  File "/home/xzy/xzy/modelscope/modelscope/models/multi_modal/mplug/modeling_mplug.py", line 2503, in __init__
    num_frames=config.num_frames)
  File "/home/xzy/xzy/modelscope/modelscope/models/multi_modal/mplug/mvit.py", line 789, in __init__
    padding=patch_padding,
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xzy/xzy/modelscope/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/xzy/xzy/modelscope/modelscope/pipelines/multi_modal/video_captioning_pipeline.py", line 31, in __init__
    super().__init__(model=model, preprocessor=preprocessor, **kwargs)
  File "/home/xzy/xzy/modelscope/modelscope/pipelines/base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "/home/xzy/xzy/modelscope/modelscope/pipelines/base.py", line 58, in initiate_single_model
    device_map=self.device_map) if is_model(model) else model
  File "/home/xzy/xzy/modelscope/modelscope/models/base/base_model.py", line 151, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/home/xzy/xzy/modelscope/modelscope/models/builder.py", line 36, in build_model
    cfg, MODELS, group_key=task_name, default_args=default_args)
  File "/home/xzy/xzy/modelscope/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: HiTeAForAllTasks: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xzy/xzy/modelscope/demo.py", line 7, in <module>
    pipeline_caption = pipeline(Tasks.video_captioning, model=model_id)
  File "/home/xzy/xzy/modelscope/modelscope/pipelines/builder.py", line 148, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/xzy/xzy/modelscope/modelscope/pipelines/builder.py", line 61, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/home/xzy/xzy/modelscope/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: VideoCaptioningPipeline: HiTeAForAllTasks: 'NoneType' object is not callable

请问这是怎么回事？谢谢

**Comment by Xiyu-AI** [comment]
解决了，看到之前有前辈也发生了这样的错误
在环境安装这个包就行了：pip install fairscale
