### ISSUE TITLE
为什么总是限流啊，

### ISSUE THREAD

**Issue by 66li** [modelscope/modelscope#496]
--------uuid:  qw|██▍       | 791M/3.20G [01:20<18:37, 2.33MB/s]
----------work_dir:  /tmp/qw/personalizaition_lora
                                                                 Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(<25:27, 1.17MB/s]
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 197, in run
    data_process_fn(instance_data_dir, True)
  File "/facechain/facechain/inference.py", line 23, in data_process_fn
    data_process_fn = Blipv2()
  File "/facechain/facechain/data_process/preprocessing.py", line 202, in __init__
    self.model = DeepDanbooru()
  File "/facechain/facechain/data_process/deepbooru.py", line 721, in __init__
    snapshot_path = snapshot_download(foundation_model_id, revision='v4.0')
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/snapshot_download.py", line 140, in snapshot_download
    parallel_download(
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 243, in parallel_download
    list(executor.map(download_part, tasks))
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 206, in download_part
    progress.update(len(chunk))
OSError: [Errno 5] Input/output error

下了半天了

**Comment by wenmengzhou** [comment]
您好，请检查一下您的网络，一般这种情况是网络不稳定导致

**Comment by wenmengzhou** [comment]
另外下个版本我们会加上下载重试机制避免网络问题

**Comment by liuyhwangyh** [comment]
How are you running the script？Can you provide the command?

**Comment by 66li** [comment]
阿里云的ECS

**Comment by 66li** [comment]
不应该有网络问题啊，有那种1模式可以加速阿里内网的加载速度吗

**Comment by liuyhwangyh** [comment]
OSError: [Errno 5] Input/output error说明，不是网路问题，请将运行脚本输出重定向到文件或者 /dev/null
python xxx.py >/dev/null &

**Comment by 66li** [comment]
好像确实不是网络问题，这个脚本是不是不兼容 nfs类的文件系统啊
我用的是oss映射为文件目录，往那个目录里下模型的时候就会有问题

**Comment by 66li** [comment]
是不是不支持这个
<img width="567" alt="image" src="https://github.com/modelscope/modelscope/assets/37136076/46eb9170-0149-4870-ac53-78812ab907e3">

**Comment by liuyhwangyh** [comment]
> 

这个有可能，目前模型比较大，会并发下载，并发写文件，有可能oss映射的文件系统不支持并发写。

**Comment by 66li** [comment]
能加个什么环境变量或者选项，配置一下吗

**Comment by 66li** [comment]
兼容oss的那种下载方式

**Comment by 66li** [comment]
MODELSCOPE_DOWNLOAD_PARALLELS=0
使用这个环境变了能避免并发下载吗
