### ISSUE TITLE
Error when using modelscope in python embed 

### ISSUE THREAD

**Issue by ultimatech-cn** [modelscope/modelscope#529]
I try to using  facechain with python embed on windows platform.
After install all the requirement package, run the app by

`D:\facechain_win\facechain-win>D:\facechain_win\python-3.10.11-embed-amd64\python app.py`

I got error like following
```
D:\facechain_win\facechain-win>D:\facechain_win\python-3.10.11-embed-amd64\python app-win.py
2023-09-09 21:08:50,806 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-09-09 21:08:50,807 - modelscope - INFO - Loading ast index from C:\Users\admin\.cache\modelscope\ast_indexer
2023-09-09 21:08:50,845 - modelscope - INFO - Loading done! Current index file version is 1.9.0, with md5 daef25824c7f14037762be546c7bfa52 and a total number of 921 components indexed
Traceback (most recent call last):
  File "D:\facechain_win\facechain-win\app-win.py", line 21, in <module>
    from facechain.inference import GenPortrait
  File "D:\facechain_win\facechain-win\facechain\inference.py", line 14, in <module>
    from modelscope.pipelines import pipeline
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
    from .base import Pipeline
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\pipelines\base.py", line 15, in <module>
    from modelscope.models.base import Model
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\models\__init__.py", line 8, in <module>
    from .base import Head, Model
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\models\base\__init__.py", line 4, in <module>
    from .base_head import *  # noqa F403
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\models\base\base_head.py", line 5, in <module>
    from modelscope.models.base.base_model import Model
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\models\base\base_model.py", line 16, in <module>
    from modelscope.utils.plugins import (register_modelhub_repo,
  File "D:\facechain_win\python-3.10.11-embed-amd64\Lib\site-packages\modelscope\utils\plugins.py", line 12, in <module>
    import venv
ModuleNotFoundError: No module named 'venv'
```

The  plugin.py using venv like :
```
 self.env_builder = venv.EnvBuilder(
            system_site_packages=True,
            clear=False,
            symlinks=True,
            with_pip=False)
```
I tried to install virtualenv, but it doesn't work.

D:\facechain_win>.\python-3.10.11-embed-amd64\python -m pip install virtualenv
D:\facechain_win>.\python-3.10.11-embed-amd64\python -m pip show virtualenv
Name: virtualenv
Version: 20.24.5
Summary: Virtual Python Environment builder
Home-page:
Author:
Author-email:
License:
Location: d:\facechain_win\python-3.10.11-embed-amd64\lib\site-packages
Requires: distlib, filelock, platformdirs
Required-by:

Any suggestion for me?  Any workround for this?

**Comment by wenmengzhou** [comment]
[venv](https://docs.python.org/3/library/venv.html) is a package that comes with Python 3.  Check whether it is in your python package

**Comment by ultimatech-cn** [comment]
> [venv](https://docs.python.org/3/library/venv.html) is a package that comes with Python 3. Check whether it is in your python package

Thanks！ I solved the problem by import virtualenv as venv.
