### ISSUE TITLE
nlp throw exceptions

### ISSUE THREAD

**Issue by jasstionzyf** [modelscope/modelscope#53]
Traceback (most recent call last):
  File "./comm.py", line 902, in <module>
    testModelScopeNlp()
  File "./comm.py", line 830, in testModelScopeNlp
    task=Tasks.translation, model="damo/nlp_csanmt_translation_zh2en"
  File "/data/apps/miniconda3/envs/modelscope-nlp/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 352, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/data/apps/miniconda3/envs/modelscope-nlp/lib/python3.7/site-packages/modelscope/pipelines/builder.py", line 270, in build_pipeline
    cfg, PIPELINES, group_key=task_name, default_args=default_args)
  File "/data/apps/miniconda3/envs/modelscope-nlp/lib/python3.7/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
NotImplementedError: TranslationPipeline: Cannot convert a symbolic Tensor (NmtModel/strided_slice_3:0) to a numpy array.

**Comment by jasstionzyf** [comment]
tensorflow should be 2.x , 官方文档说的是1.15，文档需要更新了。
