### ISSUE TITLE
The `relative_file_dirs` missed __init__.py

### ISSUE THREAD

**Issue by wadeok** [modelscope/modelscope#539]
我在运行`inference = pipeline('talking-head', model='wwd123/sadtalker', model_revision='v1.0.1')`时遇到报错：”cannot import name 'get_model' from 'src.face3d.models.arcface_torch.backbones'“，经查，这是因为我的src.face3d.models.arcface_torch.backbones目录下的__init__.py里面是有代码的：
![image](https://github.com/modelscope/modelscope/assets/138575543/b74b58a4-15a8-490c-bacd-22417d0f3b36)
而通过`def create_module_from_files`拷贝到modelscope_module目录下时被`def create_empty_file`调用生成了一个空的__init__.py，里面的代码消失导致import错误，据我观察，__init__.py里面有代码是很常见的，应该把原来的__init__.py也拷贝到modelscope_module去。我又查了一下，`relative_file_dirs`这个变量列表里已经不包含__init__.py文件了，再往上溯源，就是`class FilesAstScanning`在执行`def _traversal_files`时，跳过了__开头的.py文件，而我将`item.name.startswith('__') or`删了之后，
![image](https://github.com/modelscope/modelscope/assets/138575543/dd46c834-593d-41bf-84bb-5e7a555585be)
又遇到了报错：
```
Traceback (most recent call last):
  File "d:\repos\test.py", line 1, in <module>
    from modelscope.models import Model
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import LazyImportModule
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\__init__.py", line 1, in <module>
    from .hub import create_model_if_not_exist, read_config
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\hub.py", line 12, in <module>
    from modelscope.utils.config import Config
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\config.py", line 22, in 
<module>
    from modelscope.utils.import_utils import import_modules_from_file
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\import_utils.py", line 367, in <module>
    class LazyImportModule(ModuleType):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\import_utils.py", line 370, in LazyImportModule
    AST_INDEX = load_index()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\ast_utils.py", line 719, in load_index
    _update_index(index, files_mtime)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\ast_utils.py", line 635, in _update_index
    updated_index = file_scanner.get_files_scan_results(updated_files)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\ast_utils.py", line 529, in get_files_scan_results
    decorator_list, import_list = self._get_single_file_scan_result(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\ast_utils.py", line 466, in _get_single_file_scan_result
    raise Exception(
Exception: During ast indexing the file C:\Users\xxx\AppData\Local\Programs\Python\Python310\Lib\site-packages\modelscope\models\cv\image_inpainting\modules\__init__.py, a related error excepted in the file C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\modelscope\utils\ast_utils.py at line: 366: "output[DECORATOR_KEY] = self.parse_decorators(output[DECORATOR_KEY])" with error msg: "KeyError: 'decorators'", please double check the origin file C:\Users\xxx\AppData\Local\Programs\Python\Python310\Lib\site-packages\modelscope\models\cv\image_inpainting\modules\__init__.py to see whether the file is correctly edited.
```

**Comment by wadeok** [comment]
It can now successfully copy the complete __init__.py file to modelscope_modules folder, thanks !
