### ISSUE TITLE
官方示例出错

### ISSUE THREAD

**Issue by ubuntu733** [modelscope/modelscope#56]
示例来源 https://modelscope.cn/datasets/modelscope/Alimeeting4MUG/summary
示例代码
```
from modelscope.hub.api import HubApi
from modelscope.msdatasets import MsDataset
from modelscope.utils.constant import DownloadMode
api = HubApi()
sdk_token = "-----------"  # 必填, 从modelscope WEB端个人中心获取
api.login(sdk_token)  # online
input_config_kwargs = {'delimiter': '\t'}
data = MsDataset.load(
    'Alimeeting4MUG',
    namespace='modelscope',
    download_mode=DownloadMode.FORCE_REDOWNLOAD,
    subset_name="only_topic_segmentation",
    **input_config_kwargs)
    
print(data["test"][0])
```
错误返回
```
Traceback (most recent call last):
  File "SpokenNLP/test.py", line 13, in <module>
    **input_config_kwargs)
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/modelscope/msdatasets/ms_dataset.py", line 202, in load
    **config_kwargs)
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/modelscope/msdatasets/ms_dataset.py", line 252, in _load_ms_dataset
    **config_kwargs)
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/load.py", line 1681, in load_dataset
    **config_kwargs,
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/load.py", line 1453, in load_dataset_builder
    data_files=data_files,
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/load.py", line 1105, in dataset_module_factory
    path, data_dir=data_dir, data_files=data_files, download_mode=download_mode
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/load.py", line 631, in get_module
    allowed_extensions=ALL_ALLOWED_EXTENSIONS,
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/data_files.py", line 801, in from_local_or_remote
    if not isinstance(patterns_for_key, DataFilesList)
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/data_files.py", line 763, in from_local_or_remote
    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)
  File "/anaconda3/envs/nlp/lib/python3.7/site-packages/datasets/data_files.py", line 368, in resolve_patterns_locally_or_by_urls
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to resolve any data file that matches '['**[-._ 0-9/]test[-._ 0-9]*', 'test[-._ 0-9]*', '**[-._ 0-9/]testing[-._ 0-9]*', 'testing[-._ 0-9]*', '**[-._ 0-9/]eval[-._ 0-9]*', 'eval[-._ 0-9]*', '**[-._ 0-9/]evaluation[-._ 0-9]*', 'evaluation[-._ 0-9]*']' at /Users/shenchengen/source/nlp/SpokenNLP/Alimeeting4MUG with any supported extension ['csv', 'tsv', 'json', 'jsonl', 'parquet', 'txt', 'blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'msp', 'pcd', 'pxr', 'pbm', 'pgm', 'ppm', 'pnm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm', 'BLP', 'BMP', 'DIB', 'BUFR', 'CUR', 'PCX', 'DCX', 'DDS', 'PS', 'EPS', 'FIT', 'FITS', 'FLI', 'FLC', 'FTC', 'FTU', 'GBR', 'GIF', 'GRIB', 'H5', 'HDF', 'PNG', 'APNG', 'JP2', 'J2K', 'JPC', 'JPF', 'JPX', 'J2C', 'ICNS', 'ICO', 'IM', 'IIM', 'TIF', 'TIFF', 'JFIF', 'JPE', 'JPG', 'JPEG', 'MPG', 'MPEG', 'MSP', 'PCD', 'PXR', 'PBM', 'PGM', 'PPM', 'PNM', 'PSD', 'BW', 'RGB', 'RGBA', 'SGI', 'RAS', 'TGA', 'ICB', 'VDA', 'VST', 'WEBP', 'WMF', 'EMF', 'XBM', 'XPM', 'aiff', 'au', 'avr', 'caf', 'flac', 'htk', 'svx', 'mat4', 'mat5', 'mpc2k', 'ogg', 'paf', 'pvf', 'raw', 'rf64', 'sd2', 'sds', 'ircam', 'voc', 'w64', 'wav', 'nist', 'wavex', 'wve', 'xi', 'mp3', 'opus', 'AIFF', 'AU', 'AVR', 'CAF', 'FLAC', 'HTK', 'SVX', 'MAT4', 'MAT5', 'MPC2K', 'OGG', 'PAF', 'PVF', 'RAW', 'RF64', 'SD2', 'SDS', 'IRCAM', 'VOC', 'W64', 'WAV', 'NIST', 'WAVEX', 'WVE', 'XI', 'MP3', 'OPUS', 'zip']
```
modelscope == 1.1.0

**Comment by PerfeZ** [comment]
这个问题还存在吗？

**Comment by yingdachen** [comment]
fixed as "fail-to-reproduce"
