### ISSUE TITLE
The "freeze_support()" line can be omitted if the program         is not going to be frozen to produce an executable.

### ISSUE THREAD

**Issue by monkeycc** [modelscope/modelscope#565]
https://www.modelscope.cn/models/damo/cv_nafnet_image-deblur_gopro/summary
```python

import os
import tempfile

from modelscope.hub.snapshot_download import snapshot_download
from modelscope.msdatasets import MsDataset
from modelscope.msdatasets.task_datasets.gopro_image_deblurring_dataset import \
    GoproImageDeblurringDataset
from modelscope.trainers import build_trainer
from modelscope.utils.config import Config
from modelscope.utils.constant import DownloadMode, ModelFile

tmp_dir = tempfile.TemporaryDirectory().name
if not os.path.exists(tmp_dir):
    os.makedirs(tmp_dir)
model_id = 'damo/cv_nafnet_image-deblur_gopro'
cache_path = snapshot_download(model_id)
config = Config.from_file(
    os.path.join(cache_path, ModelFile.CONFIGURATION))

dataset_train = MsDataset.load(
    'GOPRO',
    namespace='damo',
    subset_name='default',
    split='test',
    download_mode=DownloadMode.REUSE_DATASET_IF_EXISTS)._hf_ds
dataset_val = MsDataset.load(
    'GOPRO',
    namespace='damo',
    subset_name='subset',
    split='test',
    download_mode=DownloadMode.REUSE_DATASET_IF_EXISTS)._hf_ds

dataset_train = GoproImageDeblurringDataset(
            dataset_train, config.dataset, is_train=True)
dataset_val = GoproImageDeblurringDataset(
    dataset_val, config.dataset, is_train=False)

kwargs = dict(
    model=model_id,
    train_dataset=dataset_train,
    eval_dataset=dataset_val,
    work_dir=tmp_dir)
trainer = build_trainer(default_args=kwargs)
trainer.train()
```

报错

```

python modelscope_NAFNet_Tian.py
2023-09-26 16:02:24,208 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2023-09-26 16:02:24,209 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-09-26 16:02:24,319 - modelscope - INFO - Loading done! Current index file version is 1.9.1, with md5 7f40f255a63b4847fd672a2111cecf95 and a total number of 924 components indexed
2023-09-26 16:02:24,826 - modelscope - WARNING - The reference has been Deprecated in modelscope v1.4.0+, please use `from modelscope.msdatasets.dataset_cls.custom_datasets import GoproImageDeblurringDataset`
2023-09-26 16:02:25,413 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:26,412 - modelscope - WARNING - Reusing dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:26,412 - modelscope - INFO - Generating dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:26,412 - modelscope - INFO - Reusing cached meta-data file: C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files\ef8ecd54a765b872447ceca8fc98b82b
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.27it/s]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1002.46it/s]
2023-09-26 16:02:29,334 - modelscope - WARNING - Reusing dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:29,334 - modelscope - INFO - Generating dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:29,335 - modelscope - INFO - Reusing cached meta-data file: C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files\aeeabc9dad69c18072bec592faef63bc
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.34it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 622.76it/s]
2023-09-26 16:02:30,431 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:31,038 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:31,508 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:31,725 - modelscope - INFO - initialize model from C:\Users\monke\.cache\modelscope\hub\damo\cv_nafnet_image-deblur_gopro
2023-09-26 16:02:32,026 - modelscope - INFO - Loading NAFNet model from C:\Users\monke\.cache\modelscope\hub\damo\cv_nafnet_image-deblur_gopro\pytorch_model.pt, with param key: [params].
2023-09-26 16:02:32,131 - modelscope - INFO - load model done.
2023-09-26 16:02:32,313 - modelscope - INFO - ==========================Training Config Start==========================
2023-09-26 16:02:32,313 - modelscope - INFO - {
    "framework": "pytorch",
    "task": "image-deblurring",
    "pipeline": {
        "type": "nafnet-image-deblur"
    },
    "model": {
        "type": "nafnet",
        "network_g": {
            "img_channel": 3,
            "width": 64,
            "middle_blk_num": 1,
            "enc_blk_nums": [
                1,
                1,
                1,
                28
            ],
            "dec_blk_nums": [
                1,
                1,
                1,
                1
            ]
        }
    },
    "dataset": {
        "name": "SIDD",
        "type": "PairedImageDataset",
        "dataroot_gt": "data/GOPRO_example/",
        "dataroot_lq": "data/GOPRO_example/",
        "filename_tmpl": "{}",
        "scale": 1,
        "gt_size": 256,
        "use_flip": false,
        "use_rot": false
    },
    "preprocessor": {
        "type": "image-deblur-preprocessor"
    },
    "train": {
        "dataloader": {
            "batch_size_per_gpu": 2,
            "workers_per_gpu": 4,
            "shuffle": true
        },
        "optimizer": {
            "type": "AdamW",
            "lr": 1e-05,
            "weight_decay": 0.001,
            "betas": [
                0.9,
                0.9
            ]
        },
        "lr_scheduler": {
            "type": "CosineAnnealingLR",
            "T_max": 400000,
            "eta_min": 1e-07
        },
        "max_epochs": 1,
        "hooks": [
            {
                "type": "IterTimerHook"
            }
        ],
        "checkpoint": {
            "period": {
                "interval": 1
            }
        },
        "logging": {
            "interval": 1
        },
        "work_dir": "C:\\Users\\monke\\AppData\\Local\\Temp\\tmpfv82pa_f"
    },
    "evaluation": {
        "dataloader": {
            "batch_size_per_gpu": 1,
            "workers_per_gpu": 1,
            "shuffle": false
        },
        "period": {
            "interval": 1
        }
    }
}
2023-09-26 16:02:32,314 - modelscope - INFO - ===========================Training Config End===========================
2023-09-26 16:02:32,314 - modelscope - WARNING - ('OPTIMIZER', 'default', 'AdamW') not found in ast index file
2023-09-26 16:02:32,316 - modelscope - WARNING - ('LR_SCHEDULER', 'default', 'CosineAnnealingLR') not found in ast index file
2023-09-26 16:02:32,318 - modelscope - INFO - Stage: before_run:
    (ABOVE_NORMAL) OptimizerHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: before_train_epoch:
    (LOW         ) LrSchedulerHook
 --------------------
Stage: before_train_iter:
    (ABOVE_NORMAL) OptimizerHook
 --------------------
Stage: after_train_iter:
    (ABOVE_NORMAL) OptimizerHook
    (NORMAL      ) EvaluationHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_train_epoch:
    (NORMAL      ) EvaluationHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_val_epoch:
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_run:
    (LOW         ) CheckpointHook
 --------------------
2023-09-26 16:02:32,426 - modelscope - INFO - Checkpoints will be saved to C:\Users\monke\AppData\Local\Temp\tmpfv82pa_f
2023-09-26 16:02:32,426 - modelscope - INFO - Text logs will be saved to C:\Users\monke\AppData\Local\Temp\tmpfv82pa_f
2023-09-26 16:02:34,236 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2023-09-26 16:02:34,237 - modelscope - INFO - Loading ast index from C:\Users\monke\.cache\modelscope\ast_indexer
2023-09-26 16:02:34,351 - modelscope - INFO - Loading done! Current index file version is 1.9.1, with md5 7f40f255a63b4847fd672a2111cecf95 and a total number of 924 components indexed
2023-09-26 16:02:34,849 - modelscope - WARNING - The reference has been Deprecated in modelscope v1.4.0+, please use `from modelscope.msdatasets.dataset_cls.custom_datasets import GoproImageDeblurringDataset`
2023-09-26 16:02:35,250 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:36,032 - modelscope - WARNING - Reusing dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:36,032 - modelscope - INFO - Generating dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:36,034 - modelscope - INFO - Reusing cached meta-data file: C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files\ef8ecd54a765b872447ceca8fc98b82b
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.12it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
2023-09-26 16:02:38,894 - modelscope - WARNING - Reusing dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:38,894 - modelscope - INFO - Generating dataset gopro (C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files)
2023-09-26 16:02:38,894 - modelscope - INFO - Reusing cached meta-data file: C:\Users\monke\.cache\modelscope\hub\datasets\damo\GOPRO\master\data_files\aeeabc9dad69c18072bec592faef63bc
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.59it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 958.26it/s]
2023-09-26 16:02:40,025 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:40,748 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:41,231 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.1
2023-09-26 16:02:41,540 - modelscope - INFO - initialize model from C:\Users\monke\.cache\modelscope\hub\damo\cv_nafnet_image-deblur_gopro
2023-09-26 16:02:41,839 - modelscope - INFO - Loading NAFNet model from C:\Users\monke\.cache\modelscope\hub\damo\cv_nafnet_image-deblur_gopro\pytorch_model.pt, with param key: [params].
2023-09-26 16:02:41,953 - modelscope - INFO - load model done.
2023-09-26 16:02:42,161 - modelscope - INFO - ==========================Training Config Start==========================
2023-09-26 16:02:42,161 - modelscope - INFO - {
    "framework": "pytorch",
    "task": "image-deblurring",
    "pipeline": {
        "type": "nafnet-image-deblur"
    },
    "model": {
        "type": "nafnet",
        "network_g": {
            "img_channel": 3,
            "width": 64,
            "middle_blk_num": 1,
            "enc_blk_nums": [
                1,
                1,
                1,
                28
            ],
            "dec_blk_nums": [
                1,
                1,
                1,
                1
            ]
        }
    },
    "dataset": {
        "name": "SIDD",
        "type": "PairedImageDataset",
        "dataroot_gt": "data/GOPRO_example/",
        "dataroot_lq": "data/GOPRO_example/",
        "filename_tmpl": "{}",
        "scale": 1,
        "gt_size": 256,
        "use_flip": false,
        "use_rot": false
    },
    "preprocessor": {
        "type": "image-deblur-preprocessor"
    },
    "train": {
        "dataloader": {
            "batch_size_per_gpu": 2,
            "workers_per_gpu": 4,
            "shuffle": true
        },
        "optimizer": {
            "type": "AdamW",
            "lr": 1e-05,
            "weight_decay": 0.001,
            "betas": [
                0.9,
                0.9
            ]
        },
        "lr_scheduler": {
            "type": "CosineAnnealingLR",
            "T_max": 400000,
            "eta_min": 1e-07
        },
        "max_epochs": 1,
        "hooks": [
            {
                "type": "IterTimerHook"
            }
        ],
        "checkpoint": {
            "period": {
                "interval": 1
            }
        },
        "logging": {
            "interval": 1
        },
        "work_dir": "C:\\Users\\monke\\AppData\\Local\\Temp\\tmpcjjkycjr"
    },
    "evaluation": {
        "dataloader": {
            "batch_size_per_gpu": 1,
            "workers_per_gpu": 1,
            "shuffle": false
        },
        "period": {
            "interval": 1
        }
    }
}
2023-09-26 16:02:42,171 - modelscope - INFO - ===========================Training Config End===========================
2023-09-26 16:02:42,172 - modelscope - WARNING - ('OPTIMIZER', 'default', 'AdamW') not found in ast index file
2023-09-26 16:02:42,174 - modelscope - WARNING - ('LR_SCHEDULER', 'default', 'CosineAnnealingLR') not found in ast index file
2023-09-26 16:02:42,176 - modelscope - INFO - Stage: before_run:
    (ABOVE_NORMAL) OptimizerHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: before_train_epoch:
    (LOW         ) LrSchedulerHook
 --------------------
Stage: before_train_iter:
    (ABOVE_NORMAL) OptimizerHook
 --------------------
Stage: after_train_iter:
    (ABOVE_NORMAL) OptimizerHook
    (NORMAL      ) EvaluationHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_train_epoch:
    (NORMAL      ) EvaluationHook
    (LOW         ) LrSchedulerHook
    (LOW         ) CheckpointHook
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_val_epoch:
    (VERY_LOW    ) TextLoggerHook
 --------------------
Stage: after_run:
    (LOW         ) CheckpointHook
 --------------------
2023-09-26 16:02:42,282 - modelscope - INFO - Checkpoints will be saved to C:\Users\monke\AppData\Local\Temp\tmpcjjkycjr
2023-09-26 16:02:42,284 - modelscope - INFO - Text logs will be saved to C:\Users\monke\AppData\Local\Temp\tmpcjjkycjr
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "E:\2023_Code\py_2023\modelscope_NAFNet_Tian.py", line 53, in <module>
    trainer.train()
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\site-packages\modelscope\trainers\trainer.py", line 700, in train
    self.train_loop(self.train_dataloader)
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\site-packages\modelscope\trainers\trainer.py", line 1214, in train_loop
    for i, data_batch in enumerate(data_loader):
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 441, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\site-packages\torch\utils\data\dataloader.py", line 1042, in __init__
    w.start()
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\monke\.conda\envs\GradioYolov8\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

```

**Comment by ycwdaaaa** [comment]
我也遇到这个问题了， 请问你是怎么解决的
