### ISSUE TITLE
 Authentication token does not exist, failed to access model unknown which may not exist or may be   private. Please login first.

### ISSUE THREAD

**Issue by 2656657838** [modelscope/modelscope#568]
训练时报错
2023-09-27 15:17:54,332 - modelscope - INFO - load ./zhong_data/output_dir/
2023-09-27 15:17:54,555 - modelscope - ERROR - Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
2023-09-27 15:17:54,652 - modelscope - ERROR - Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.

**Comment by wenmengzhou** [comment]
在训练前执行如下代码登录，使用自己的私有仓库
```python
from modelscope.hub.api import HubApi

YOUR_ACCESS_TOKEN = '请从ModelScope个人中心->访问令牌获取'

api = HubApi()
api.login(YOUR_ACCESS_TOKEN)
```

**Comment by ArlanCooper** [comment]
我就是仅仅运行一下本地模型，为什么还报这个错误呢：

**Comment by Xiaoyang-Lu** [comment]
> 我就是仅仅运行一下本地模型，为什么还报这个错误呢： 运行命令:
> 
> ```
> from vllm import LLM, SamplingParams
> llm = LLM(model="/data/share/rwq/Qwen-7B-Chat", revision="v1.1.8", trust_remote_code=True)
> ```
> 
> 报错:
> 
> ```
> 2024-01-03 17:58:31,460 - modelscope - ERROR - Authentication token does not exist, failed to access model /data/share/rwq/Qwen-7B-Chat which may not exist or may be                 private. Please login first.
> ```
> 
> 请问是什么原因？
> 
> 我的python版本是: python 3.10.12

@ArlanCooper 请问问题解决了吗？我运行vllm也有同样困扰。

**Comment by Xiaoyang-Lu** [comment]
> 在训练前执行如下代码登录，使用自己的私有仓库
> 
> ```python
> from modelscope.hub.api import HubApi
> 
> YOUR_ACCESS_TOKEN = '请从ModelScope个人中心->访问令牌获取'
> 
> api = HubApi()
> api.login(YOUR_ACCESS_TOKEN)
> ```

您好，我按照您提供的方法，但是却出现以下问题：
```
2024-01-27 17:54:55,878 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-01-27 17:54:55,878 - modelscope - INFO - Loading ast index from /home/cc/.cache/modelscope/ast_indexer
2024-01-27 17:54:55,997 - modelscope - INFO - Loading done! Current index file version is 1.11.1, with md5 c9b988ee25325c806355d2d6d2c50417 and a total number of 956 components indexed
Traceback (most recent call last):
File "/home/cc/vllm/examples/./offline_inference.py", line 6, in
api.login(YOUR_ACCESS_TOKEN)
File "/home/cc/.local/lib/python3.9/site-packages/modelscope/hub/api.py", line 111, in login
raise_for_http_status(r)
File "/home/cc/.local/lib/python3.9/site-packages/modelscope/hub/errors.py", line 175, in raise_for_http_status
raise HTTPError(http_error_msg, response=rsp)
requests.exceptions.HTTPError: 400 Client Error: Bad Request, Request id: 138622c79212439ebdc255de54693400 for url: https://www.modelscope.cn/api/v1/login, body: b'{"AccessToken": "xxx.....xxxxx"}'
```

请问您有什么解决方法吗？

**Comment by gxy-gxy** [comment]
@ArlanCooper 请问您解决了吗，我遇到了相同的问题

**Comment by gxy-gxy** [comment]
@ArlanCooper 我解决了，只要`unset VLLM_USE_MODELSCOPE`就行

**Comment by ArlanCooper** [comment]
> @ArlanCooper 我解决了，只要`unset VLLM_USE_MODELSCOPE`就行

就是不用modelscope吗？只使用transformers吧？

**Comment by zhangyuygss** [comment]
Same error comes together with `TypeError: Accelerator.__init__() got an unexpected keyword argument 'use_seedable_sampler'`,
update accelarator solves it: `pip install accelerate==0.27.2`
