### ISSUE TITLE
案例运行报错

### ISSUE THREAD

**Issue by llwc594** [modelscope/modelscope#577]
Traceback (most recent call last):
  File "F:\CLIP\1.py", line 87, in <module>
    trainer.train()
  File "F:\CLIP\venvs\lib\site-packages\modelscope\trainers\trainer.py", line 699, in train
    self.train_loop(self.train_dataloader)
  File "F:\CLIP\venvs\lib\site-packages\modelscope\trainers\trainer.py", line 1213, in train_loop
    for i, data_batch in enumerate(data_loader):
  File "F:\CLIP\venvs\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "F:\CLIP\venvs\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\CLIP\venvs\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "F:\python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\python\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\python\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MsDataset._to_torch_dataset_with_processors.<locals>.MsMapDataset'
在运行官方案例的时候报了这个错误，不知道是什么原因，该怎么修改？
网站：https://modelscope.cn/docs/CLIP_CN_Tutorial#3.3.1%20%E5%87%86%E5%A4%87%E8%AE%AD%E7%BB%83%E8%B6%85%E5%8F%82

**Comment by llwc594** [comment]
'dataloader': {'batch_size_per_gpu': 1,
                                # 训练DataLoader使用进程数，0代表直接主进程读取数据
                                'workers_per_gpu': 0,
                                最终是修改了这里的参数，运行正常了
