### ISSUE TITLE
语音合成报错 TtsFrontendInitializeFailedException: modelscope error: resource invalid:

### ISSUE THREAD

**Issue by 88pmbfs88** [modelscope/modelscope#628]
语音合成的本地环境安装完成，使用示例代码提示tts初始化失败，原因是模型resource报文，不知道怎么回事，有谁遇到过这样的报错没？
系统是：ubuntu-22.04.3-desktop-amd64
模型：speech_sambert-hifigan_tts_zh-cn_16k

Model related: @wenmengzhou @tastelikefeet

报错

(vnvoice-mk) gc@gc-virtual-machine:~/dev_workspace/speech_maker$ python main.py 
2023-11-09 10:24:44,153 - modelscope - INFO - PyTorch version 1.11.0+cpu Found.
2023-11-09 10:24:44,155 - modelscope - INFO - TensorFlow version 2.13.1 Found.
2023-11-09 10:24:44,155 - modelscope - INFO - Loading ast index from /home/gc/.cache/modelscope/ast_indexer
2023-11-09 10:24:44,201 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 7807628605ed520101ce8a97ae629f81 and a total number of 945 components indexed
2023-11-09 10:24:47,206 - modelscope - WARNING - Model revision not specified, use revision: v1.0.2
2023-11-09 10:24:53,034 - modelscope - INFO - initiate model from /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k
2023-11-09 10:24:53,034 - modelscope - INFO - initiate model from location /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k.
2023-11-09 10:24:53,036 - modelscope - INFO - initialize model from /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k
2023-11-09 10:24:53,040 - modelscope - INFO - am_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/am/config.yaml voc_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/voc/config.yaml
2023-11-09 10:24:53,040 - modelscope - INFO - audio_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/audio_config.yaml
2023-11-09 10:24:53,040 - modelscope - INFO - am_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/am/ckpt/checkpoint_0.pth')])
2023-11-09 10:24:53,040 - modelscope - INFO - voc_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/voc/ckpt/checkpoint_0.pth'), (1, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/voc/ckpt/checkpoint_1.pth')])
2023-11-09 10:24:53,040 - modelscope - INFO - se_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/am/se.npy se_model_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/se/ckpt/se.onnx
2023-11-09 10:24:53,040 - modelscope - INFO - mvn_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhitian_emo/am/mvn.npy
2023-11-09 10:24:53,072 - modelscope - INFO - am_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/am/config.yaml voc_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/voc/config.yaml
2023-11-09 10:24:53,072 - modelscope - INFO - audio_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/audio_config.yaml
2023-11-09 10:24:53,072 - modelscope - INFO - am_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/am/ckpt/checkpoint_0.pth')])
2023-11-09 10:24:53,072 - modelscope - INFO - voc_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/voc/ckpt/checkpoint_0.pth'), (1, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/voc/ckpt/checkpoint_1.pth')])
2023-11-09 10:24:53,072 - modelscope - INFO - se_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/am/se.npy se_model_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/se/ckpt/se.onnx
2023-11-09 10:24:53,072 - modelscope - INFO - mvn_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhibei_emo/am/mvn.npy
2023-11-09 10:24:53,094 - modelscope - INFO - am_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/am/config.yaml voc_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/voc/config.yaml
2023-11-09 10:24:53,095 - modelscope - INFO - audio_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/audio_config.yaml
2023-11-09 10:24:53,095 - modelscope - INFO - am_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/am/ckpt/checkpoint_0.pth')])
2023-11-09 10:24:53,095 - modelscope - INFO - voc_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/voc/ckpt/checkpoint_0.pth'), (1, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/voc/ckpt/checkpoint_1.pth')])
2023-11-09 10:24:53,095 - modelscope - INFO - se_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/am/se.npy se_model_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/se/ckpt/se.onnx
2023-11-09 10:24:53,095 - modelscope - INFO - mvn_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhizhe_emo/am/mvn.npy
2023-11-09 10:24:53,117 - modelscope - INFO - am_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/am/config.yaml voc_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/voc/config.yaml
2023-11-09 10:24:53,117 - modelscope - INFO - audio_config=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/audio_config.yaml
2023-11-09 10:24:53,117 - modelscope - INFO - am_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/am/ckpt/checkpoint_0.pth')])
2023-11-09 10:24:53,117 - modelscope - INFO - voc_ckpts=OrderedDict([(0, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/voc/ckpt/checkpoint_0.pth'), (1, '/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/voc/ckpt/checkpoint_1.pth')])
2023-11-09 10:24:53,117 - modelscope - INFO - se_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/am/se.npy se_model_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/se/ckpt/se.onnx
2023-11-09 10:24:53,117 - modelscope - INFO - mvn_path=/home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/voices/zhiyan_emo/am/mvn.npy
load leagacy transf breakmodel
load leagacy transf breakmodel
text.cc: festival_Text_init
prepare tts engine failed
Traceback (most recent call last):
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/models/audio/tts/sambert_hifi.py", line 70, in __init__
    raise TtsFrontendInitializeFailedException(
modelscope.utils.audio.tts_exceptions.TtsFrontendInitializeFailedException: modelscope error: resource invalid: /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/pipelines/audio/text_to_speech_pipeline.py", line 28, in __init__
    super().__init__(model=model, **kwargs)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
modelscope.utils.audio.tts_exceptions.TtsFrontendInitializeFailedException: SambertHifigan: modelscope error: resource invalid: /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    sambert_hifigan_tts = pipeline(task=Tasks.text_to_speech, model=model_id)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 164, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/pipelines/builder.py", line 67, in build_pipeline
    return build_from_cfg(
  File "/home/gc/anaconda3/envs/vnvoice-mk/lib/python3.8/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
modelscope.utils.audio.tts_exceptions.TtsFrontendInitializeFailedException: TextToSpeechSambertHifiganPipeline: SambertHifigan: modelscope error: resource invalid: /home/gc/.cache/modelscope/hub/damo/speech_sambert-hifigan_tts_zh-cn_16k/resource

**Comment by chenlike** [comment]
```bash
pip install ttsfrd==0.2.1 -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
```
我装了这个就好了,看了一下modelscope 官方notebook的版本

**Comment by 88pmbfs88** [comment]
> ```shell
> pip install ttsfrd==0.2.1 -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
> ```
> 
> 我装了这个就好了,看了一下modelscope 官方notebook的版本

十分感谢，装了这个版本确实成功了，👌
