### ISSUE TITLE
模型：GTE文本向量-中文-通用领域-large   的训练问题

### ISSUE THREAD

**Issue by Ke51n** [modelscope/modelscope#704]
依照摩搭社区（https://modelscope.cn/models/damo/nlp_gte_sentence-embedding_chinese-large/summary）提供的训练脚本，出现如下问题，请问如何解决
Traceback (most recent call last):
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/trainers/nlp/sentence_embedding_trainer.py", line 76, in __init__
    super().__init__(
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/trainers/nlp_trainer.py", line 56, in __init__
    super().__init__(*args, **kwargs)
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/trainers/trainer.py", line 167, in __init__
    self.cfg = self.rebuild_config(self.cfg)
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/trainers/nlp_trainer.py", line 88, in rebuild_config
    if not hasattr(cfg.model, 'label2id') and not hasattr(
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/utils/config.py", line 296, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/utils/config.py", line 55, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wk/wkstation/retrival/GTE/train.py", line 66, in <module>
    trainer = build_trainer(
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/trainers/builder.py", line 39, in build_trainer
    return build_from_cfg(cfg, TRAINERS, default_args=default_args)
  File "/home/wk/.conda/envs/torch/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: SentenceEmbeddingTrainer: 'ConfigDict' object has no attribute 'model'

**Comment by slin000111** [comment]
在镜像registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0中运行模型卡片上的训练脚本无报错。modelscope版本1.10.0。
