### ISSUE TITLE
Dataset with MsDataset error

### ISSUE THREAD

**Issue by candygocandy** [modelscope/modelscope#708]
https://modelscope.cn/datasets/AI-ModelScope/stack-exchange-paired/files

I see **data/evaluation** in the file list. However, when I do:

```
from modelscope.msdatasets import MsDataset
ds =  MsDataset.load('AI-ModelScope/stack-exchange-paired', subset_name='evaluation')
```

it says:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/ms_dataset.py", line 255, in load
    dataset_inst = RemoteDataLoaderManager(
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
    oss_data_loader.process()
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 74, in process
    self._build()
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 102, in _build
    meta_manager.parse_dataset_structure()
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/meta/data_meta_manager.py", line 130, in parse_dataset_structure
    target_subset_name, target_dataset_structure = get_target_dataset_structure(
  File "/root/miniconda3/lib/python3.8/site-packages/modelscope/msdatasets/utils/dataset_utils.py", line 57, in get_target_dataset_structure
    raise ValueError(
ValueError: subset_name evaluation not found. Available: dict_keys(['default', 'finetune', 'reward', 'rl'])

**Comment by slin000111** [comment]
Here is an example：
ds =  MsDataset.load('AI-ModelScope/stack-exchange-paired', subset_name='default', split='train')
Maybe you will find some useful information in the file stack-exchange-paired/stack-exchange-paired.json
