### ISSUE TITLE
图片生成的Pipeline和NLP任务纠结在一起了

### ISSUE THREAD

**Issue by is** [modelscope/modelscope#724]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
使用StableDiffusion XL, 结果依赖ChatGLM等llm模型的依赖。

**To Reproduce**
使用[官网](https://modelscope.cn/models/AI-ModelScope/stable-diffusion-xl-base-1.0/summary)提供的例子代码
```
from modelscope.utils.constant import Tasks
from modelscope.pipelines import pipeline
import cv2

pipe = pipeline(task=Tasks.text_to_image_synthesis,
                model='AI-ModelScope/stable-diffusion-xl-base-1.0',
                use_safetensors=True,
                model_revision='v1.0.0')

prompt = 'a dog'
output = pipe({'text': prompt})
cv2.imwrite('result.png', output['output_imgs'][0])

```

```
2024-01-15 21:14:04,667 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-01-15 21:14:04,668 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-01-15 21:14:04,733 - modelscope - INFO - Loading done! Current index file version is 1.11.0, with md5 ab42468469dcc2ef53ecdba98feb0b66 and a total number of 953 components indexed
2024-01-15 21:14:05,728 - modelscope - INFO - Use user-specified model revision: v1.0.0
Traceback (most recent call last):
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 450, in _get_module
    requires(module_name_full, requirements)
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 353, in requires
    raise ImportError(''.join(failed))
ImportError: 
modelscope.models.nlp.chatglm2.tokenization requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/s/v0/m0.py", line 5, in <module>
    pipe = pipeline(task=Tasks.text_to_image_synthesis, 
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 163, in pipeline
    clear_llm_info(kwargs)
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 227, in clear_llm_info
    from .nlp.llm_pipeline import ModelTypeHelper
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/pipelines/nlp/llm_pipeline.py", line 15, in <module>
    from modelscope.models.nlp import ChatGLM2Tokenizer, Llama2Tokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 435, in __getattr__
    value = getattr(module, name)
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 434, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/c/envs/sd/lib/python3.10/site-packages/modelscope/utils/import_utils.py", line 453, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import modelscope.models.nlp.chatglm2.tokenization because of the following error (look up to see its traceback):

modelscope.models.nlp.chatglm2.tokenization requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment.
```

**Your Environments (__required__)**
* OS: `uname -a`
* Linux dummy-0-nh6vf 4.19.91-26.al7.x86_64 #1 SMP Tue May 24 12:11:55 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

* CPU: `lscpu`
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            6
    BogoMIPS:            5799.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1
                         gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 
                         pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault i
                         nvpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq r
                         dseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat
                          avx512vbmi avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):     
  L1d:                   384 KiB (8 instances)
  L1i:                   256 KiB (8 instances)
  L2:                    10 MiB (8 instances)
  L3:                    48 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-15
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```
* Commit id (e.g. `a3ffc7d8`)
```
/data/s/v0# pip list|grep modelscope
modelscope               1.11.0
```
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Pipeline related: @Firmament-cyou @wenmengzhou

**Comment by slin000111** [comment]
安装AI-ModelScope/stable-diffusion-xl-base-1.0模型卡片上的依赖。
