### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by WestbrookZero** [modelscope/modelscope#739]
In Windows10, when I trained the DCT-Net model, I got the following error：
2024-01-24 17:06:39.367662: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2024-01-24 17:06:52,521 - modelscope - INFO - Iter: 0, d_loss: 0.5868567228317261, g_loss: 0.24602027237415314
0%| | 0/300000 [00:17<?, ?it/s]
Traceback (most recent call last):
File "G:/Project/Face/DCT-Net/train_localtoon.py", line 37, in
main(args)
File "G:/Project/Face/DCT-Net/train_localtoon.py", line 25, in main
trainer.train()
File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\modelscope\trainers\cv\cartoon_translation_trainer.py", line 218, in train
str('%8d' % max_steps) + '_face_result.jpg', 4)
File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\modelscope\models\cv\cartoon\utils.py", line 142, in write_batch_image
image[k] = (image[k] + 1) * 127.5
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by slin000111** [comment]
This model depends on tensorflow and numpy versions.
