### ISSUE TITLE
ValueError: Variable generator/Conv/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

### ISSUE THREAD

**Issue by WestbrookZero** [modelscope/modelscope#741]
My tensorflow-gpu version is 1.15 , when i use code to transfer to pb file , there is a error.
**code:**
exporter = CartoonTranslationExporter()
exporter.export_frozen_graph_def(
ckpt_path=ckpt_path, frozen_graph_path=pb_path)
**error:**
WARNING:tensorflow:From D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
Traceback (most recent call last):
  File "G:/Project/Face/ModelScope00/export00.py", line 55, in <module>
    ckpt_path=ckpt_path, frozen_graph_path=pb_path)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\modelscope\exporters\cv\cartoon_translation_exporter.py", line 39, in export_frozen_graph_def
    output = model(input)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\modelscope\models\cv\cartoon\model_tf.py", line 34, in __call__
    output = unet_generator(input_photo)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\modelscope\models\cv\cartoon\network.py", line 75, in unet_generator
    x0 = slim.convolution2d(inputs, channel, [7, 7], activation_fn=None)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\layers\base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 165, in build
    dtype=self.dtype)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\layers\base.py", line 461, in add_weight
    **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 712, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 550, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1761, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1752, in _model_variable_getter
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\variables.py", line 351, in model_variable
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\contrib\framework\python\ops\variables.py", line 281, in variable
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "D:\InstallPath\Develop\Anaconda3\2020.07\envs\dctnet\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 886, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable generator/Conv/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by slin000111** [comment]
Hi, model_id was not found from the above information.
