### ISSUE TITLE
modelscope - WARNING - Download interval is too small 

### ISSUE THREAD

**Issue by FurkanGozukara** [modelscope/modelscope#754]
I am trying to download Qwen/Qwen-VL and getting this error

Here the code

```
DEFAULT_CKPT_PATH = 'Qwen/Qwen-VL'

def _load_model_tokenizer(args):
    tokenizer = AutoTokenizer.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True, 
    )

    if args.cpu_only:
        device_map = "cpu"
    else:
        device_map = "cuda"

    model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
    ).eval()
    model.generation_config = GenerationConfig.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True, 
    )

    return model, tokenizer

```

Here the error

```
(venv) G:\Qwen-VL\Qwen-VL>python web_demo_mm.py
2024-02-06 05:58:10,509 - modelscope - INFO - PyTorch version 2.2.0+cu121 Found.
2024-02-06 05:58:10,510 - modelscope - INFO - Loading ast index from C:\Users\King\.cache\modelscope\ast_indexer
2024-02-06 05:58:10,511 - modelscope - INFO - No valid ast index found from C:\Users\King\.cache\modelscope\ast_indexer, generating ast index from prebuilt!
2024-02-06 05:58:10,565 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 3c01d591cf6305a9cce371917cc97dc4 and a total number of 964 components indexed
2024-02-06 05:58:13,237 - modelscope - WARNING - Model revision not specified, use revision: v1.0.3
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1.16k/1.16k [00:00<?, ?B/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1.13k/1.13k [00:00<?, ?B/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 2.04k/2.04k [00:00<?, ?B/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████| 485k/485k [00:01<00:00, 362kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████| 242k/242k [00:01<00:00, 205kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 2.10k/2.10k [00:00<?, ?B/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 5.96k/5.96k [00:00<00:00, 110kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 6.83k/6.83k [00:00<00:00, 126kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 6.03k/6.03k [00:00<00:00, 111kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 5.26k/5.26k [00:00<?, ?B/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 7.02k/7.02k [00:00<00:00, 129kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 218/218 [00:00<?, ?B/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 6.74k/6.74k [00:00<00:00, 123kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████| 107k/107k [00:00<00:00, 120kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 43.2k/43.2k [00:00<00:00, 89.5kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 2.44M/2.44M [00:01<00:00, 1.66MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 14.5k/14.5k [00:00<00:00, 52.1kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 92.4k/92.4k [00:00<00:00, 148kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 23.6k/23.6k [00:00<00:00, 91.5kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 10.0M/10.0M [00:02<00:00, 4.44MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 21.0k/21.0k [00:00<00:00, 62.8kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 173/173 [00:00<?, ?B/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████| 14.2k/14.2k [00:00<00:00, 51.3kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 8.31k/8.31k [00:00<00:00, 153kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 184kB/s]
2024-02-06 05:58:55,988 - modelscope - WARNING - Download interval is too small, use local cache
Traceback (most recent call last):
  File "G:\Qwen-VL\Qwen-VL\web_demo_mm.py", line 246, in <module>
    main()
  File "G:\Qwen-VL\Qwen-VL\web_demo_mm.py", line 240, in main
    model, tokenizer = _load_model_tokenizer(args)
  File "G:\Qwen-VL\Qwen-VL\web_demo_mm.py", line 55, in _load_model_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "G:\Qwen-VL\Qwen-VL\venv\lib\site-packages\modelscope\utils\hf_util.py", line 111, in from_pretrained
    module_obj = module_class.from_pretrained(model_dir, *model_args,
  File "G:\Qwen-VL\Qwen-VL\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "G:\Qwen-VL\Qwen-VL\venv\lib\site-packages\modelscope\utils\hf_util.py", line 74, in from_pretrained
    return ori_from_pretrained(cls, model_dir, *model_args, **kwargs)
  File "G:\Qwen-VL\Qwen-VL\venv\lib\site-packages\transformers\modeling_utils.py", line 3338, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Users\King\.cache\modelscope\hub\Qwen\Qwen-VL.
```

here the pip freeze

```
(venv) G:\Qwen-VL\Qwen-VL>pip freeze
absl-py==2.1.0
accelerate==0.26.1
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.9.3
aiosignal==1.3.1
aliyun-python-sdk-core==2.14.0
aliyun-python-sdk-kms==2.16.2
altair==5.2.0
annotated-types==0.6.0
anyio==4.2.0
async-timeout==4.0.3
attrs==23.2.0
bitsandbytes @ https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl
cachetools==5.3.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
crcmod==1.7
cryptography==42.0.2
cycler==0.12.1
datasets==2.16.1
deepspeed @ https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/deepspeed-0.11.2_cuda121-cp310-cp310-win_amd64.whl
dill==0.3.7
einops==0.7.0
exceptiongroup==1.2.0
fastapi==0.109.2
ffmpy==0.3.1
filelock==3.13.1
fonttools==4.47.2
frozenlist==1.4.1
fsspec==2023.10.0
gast==0.5.4
google-auth==2.27.0
google-auth-oauthlib==1.2.0
gradio==4.16.0
gradio_client==0.8.1
grpcio==1.60.1
h11==0.14.0
hjson==3.1.0
httpcore==1.0.2
httpx==0.26.0
huggingface-hub==0.20.3
idna==3.6
importlib-metadata==7.0.1
importlib-resources==6.1.1
Jinja2==3.1.3
jmespath==0.10.0
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.8.2
mdurl==0.1.2
modelscope==1.12.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.15
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.4
oauthlib==3.2.2
orjson==3.9.13
oss2==2.18.4
packaging==23.2
pandas==2.2.0
pillow==10.2.0
platformdirs==4.2.0
protobuf==4.25.2
psutil==5.9.8
py-cpuinfo==9.0.0
pyarrow==15.0.0
pyarrow-hotfix==0.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pycryptodome==3.20.0
pydantic==2.6.1
pydantic_core==2.16.2
pydub==0.25.1
Pygments==2.17.2
pynvml==11.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-multipart==0.0.7
pytz==2024.1
PyYAML==6.0.1
referencing==0.33.0
regex==2023.12.25
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.7.0
rpds-py==0.17.1
rsa==4.9
ruff==0.2.1
safetensors==0.4.2
scipy==1.12.0
semantic-version==2.10.0
shellingham==1.5.4
simplejson==3.19.2
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
starlette==0.36.3
sympy==1.12
tensorboard==2.15.1
tensorboard-data-server==0.7.2
tiktoken==0.5.2
tokenizers==0.15.1
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.1
torch==2.2.0+cu121
torchaudio==2.2.0+cu121
torchvision==0.17.0+cu121
tqdm==4.66.1
transformers==4.37.2
transformers-stream-generator==0.0.4
triton @ https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/triton-2.1.0-cp310-cp310-win_amd64.whl
typer==0.9.0
typing_extensions==4.9.0
tzdata==2023.4
urllib3==2.2.0
uvicorn==0.27.0.post1
websockets==11.0.3
Werkzeug==3.0.1
xformers==0.0.24
xxhash==3.4.1
yapf==0.40.2
yarl==1.9.4
zipp==3.17.0

(venv) G:\Qwen-VL\Qwen-VL>
```

**Comment by liuyhwangyh** [comment]
How do you download the model? Can you provide a complete example?

**Comment by FurkanGozukara** [comment]
I have published auto installer for both windows and runpod (linux) and batch captioner for  Qwen-VL

https://www.patreon.com/posts/sota-image-for-2-90744385

![qwn](https://github.com/modelscope/modelscope/assets/19240467/8af41708-b867-445e-8ba8-4b71cf600a41)

**Comment by mmx110** [comment]
Maybe modelscope version is too high.   https://github.com/modelscope/modelscope/issues/765
