### ISSUE TITLE
eyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

### ISSUE THREAD

**Issue by LRY1994** [modelscope/modelscope#785]
inference_16k_pipline = pipeline(
        task=Tasks.auto_speech_recognition,
        model='iic/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline'
        )

    # waveform, sample_rate = soundfile.read("/data/linry/FunASR/asr_example_粤语.wav")
    rec_result = inference_16k_pipline(audio_in="/data/linry/FunASR/asr_example_粤语.wav")
    print(rec_result)

2024-02-26 18:49:21,770 - modelscope - WARNING - ('PIPELINES', 'auto-speech-recognition', 'asr-inference') not found in ast index file
Traceback (most recent call last):
  File "/data/linry/FunASR/1-my/UniASR.py", line 24, in <module>
    offline()
  File "/data/linry/FunASR/1-my/UniASR.py", line 6, in offline
    inference_16k_pipline = pipeline(
  File "/data/linry/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/data/linry/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/data/linry/anaconda3/envs/funasr/lib/python3.10/site-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

**Comment by LRY1994** [comment]
modelscope version is 1.12.0
funasr Version: 1.0.10
