### ISSUE TITLE
我在多卡训练speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch的时候报错了

### ISSUE THREAD

**Issue by C-rawler** [modelscope/modelscope#809]
我在多卡训练的时候报了这个错误，单卡训练是没问题的
Task related config: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 185479) of binary: /opt/conda/envs/modelscope/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/modelscope/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/modelscope/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/modelscope/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

这是我的启动命令：CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node 2 finetune.py

请问有大佬知道这是什么问题吗

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update funasr and try it again. 
https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md#%E5%BE%AE%E8%B0%83
