### ISSUE TITLE
异常：assert len(self.decibel) == len(self.scores[0])  # 保证帧数一致

### ISSUE THREAD

**Issue by hhxdestiny** [modelscope/modelscope#82]
当我使用一个`wav`文件进行语音识别时抛出以下异常
```bash
Traceback (most recent call last):
  File "paraformer.py", line 28, in <module>
    rslt = inference_16k_pipline(audio_in='bylz60.wav')
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 136, in __call__
    output = self.forward(output)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 305, in forward
    inputs['asr_result'] = self.run_inference(self.cmd)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 383, in run_inference
    raw_inputs=cmd['raw_inputs'])
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/funasr/bin/asr_inference_paraformer_vad_punc.py", line 770, in _forward
    vad_results = speech2vadsegment(**batch)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/funasr/bin/asr_inference_paraformer_vad_punc.py", line 362, in __call__
    segments = self.vad_model(**batch)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/miniconda3/envs/modelscope/lib/python3.7/site-packages/funasr/models/e2e_vad.py", line 442, in forward
    assert len(self.decibel) == len(self.scores[0])  # 保证帧数一致
AssertionError
```
然后我打印了断言比较的内容
```bash
len(self.decibel): 16535, len(self.scores[0]): 16536
```
请问是`e2e_vad.py:271@ComputeDecibel`方法计算有误么？

**Comment by hhxdestiny** [comment]
用到的音频文件
[bylz_60s_16k.zip](https://github.com/modelscope/modelscope/files/10541886/bylz_60s_16k.zip)

**Comment by hhxdestiny** [comment]
* Task：Tasks.auto_speech_recognition
* Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch

**Comment by langgz** [comment]
We have fixed the bug, ref to https://github.com/alibaba-damo-academy/FunASR/issues/38
