### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.exceptions'

### ISSUE THREAD

**Issue by wenmengzhou** [modelscope/modelscope#824]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**

```text
from modelscope.pipelines import pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pai/lib/python3.9/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from .base import Pipeline
  File "/home/pai/lib/python3.9/site-packages/modelscope/pipelines/base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "/home/pai/lib/python3.9/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/home/pai/lib/python3.9/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import \
  File "/home/pai/lib/python3.9/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 24, in <module>
    from datasets.exceptions import DataFilesNotFoundError, DatasetNotFoundError
ModuleNotFoundError: No module named 'datasets.exceptions'
```

**To Reproduce**
execute  
```python
from modelscope.pipelines import pipeline
```

@wangxingjun778

**Comment by wangxingjun778** [comment]
make sure datasets>=2.16.0
