### ISSUE TITLE
下载数据集失败了

### ISSUE THREAD

**Issue by 459737087** [modelscope/modelscope#828]
Thanks for your error report and we appreciate it a lot.

**Checklist**

* I have searched the tutorial on modelscope  [doc-site](https://modelscope.cn/docs)
* I have searched related issues but cannot get the expected help.
* The bug has not been fixed in the latest version.

**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/wangxiaoxin/Downloads/test/download.py", line 6, in <module>
    ds = MsDataset.load('modelscope/Youku-AliceMind', namespace='tany0699', split='train')
  File "/opt/homebrew/lib/python3.9/site-packages/modelscope/msdatasets/ms_dataset.py", line 315, in load
    dataset_inst = remote_dataloader_manager.load_dataset(
  File "/opt/homebrew/lib/python3.9/site-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
    oss_downloader.process()
  File "/opt/homebrew/lib/python3.9/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 82, in process
    self._build()
  File "/opt/homebrew/lib/python3.9/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 109, in _build
    meta_manager.parse_dataset_structure()
  File "/opt/homebrew/lib/python3.9/site-packages/modelscope/msdatasets/meta/data_meta_manager.py", line 119, in parse_dataset_structure
    raise 'Cannot find dataset meta-files, please fetch meta from modelscope hub.'
TypeError: exceptions must derive from BaseException
```
**To Reproduce**
```
from modelscope.msdatasets.ms_dataset import MsDataset
from modelscope import HubApi
api=HubApi()
api.login('')
ds = MsDataset.load('modelscope/Youku-AliceMind', namespace='tany0699', split='train')
print(next(iter(ds)))
```

**Your Environments (__required__)**
* OS: `uname -a`
* CPU: `lscpu`
* Commit id (e.g. `a3ffc7d8`)
* You may add addition that may be helpful for locating the problem, such as
    * How you installed PyTorch [e.g., pip, conda, source]
    * Other environment variables that may be related (such as $PATH, $LD_LIBRARY_PATH, $PYTHONPATH, etc.)

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by wangxingjun778** [comment]
Please follow examples on the website: https://modelscope.cn/datasets/modelscope/Youku-AliceMind/summary
We recommend to use `use_streaming=True`.

For example: 

ds = MsDataset.load('modelscope/Youku-AliceMind', subset_name='classification', split='validation', use_streaming=True)
print(next(iter(ds)))

**Comment by 459737087** [comment]
Done！
