### ISSUE TITLE
ImportError: cannot import name '_datasets_server' from 'datasets.utils' 

### ISSUE THREAD

**Issue by infatuation0215** [modelscope/modelscope#836]
依照文档安装modelscope后，运行了使用pipeline的样例代码，出现如下报错，该如何解决？
Traceback (most recent call last):
  File "D:\design\model\modelscope_test.py", line 1, in <module>
    from modelscope.msdatasets import MsDataset
  File "D:\anaconda\envs\pytorch\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "D:\anaconda\envs\pytorch\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import \
  File "D:\anaconda\envs\pytorch\lib\site-packages\modelscope\msdatasets\utils\hf_datasets_util.py", line 42, in <module>
    from datasets.utils import _datasets_server, file_utils
ImportError: cannot import name '_datasets_server' from 'datasets.utils' (D:\anaconda\envs\pytorch\lib\site-packages\datasets\utils\__init__.py)

**Comment by zyeternity** [comment]
好像是 “modelscope包依赖的datasets最新版本2.19.0无法向下兼容，请将其暂时手动限制在<=2.18.0, >=2.16.0 ” 我的是这样解决的
`pip install datasets==2.18.0`

**Comment by infatuation0215** [comment]
> 好像是 “modelscope包依赖的datasets最新版本2.19.0无法向下兼容，请将其暂时手动限制在<=2.18.0, >=2.16.0 ” 我的是这样解决的 `pip install datasets==2.18.0`

问题已解决，十分感谢
