### ISSUE TITLE
Run from modelscope.pipelines import pipeline met error on the latest modelscope

### ISSUE THREAD

**Issue by ZhichaoDuan** [modelscope/modelscope#855]
When I run from modelscope.pipelines import pipeline and I met the following error:
Traceback (most recent call last):
  File "/root/codes/translate/playground.py", line 1, in <module>
    from modelscope.pipelines import pipeline
  File "/opt/conda/lib/python3.10/site-packages/modelscope/pipelines/__init__.py", line 4, in <module>
    from .base import Pipeline
  File "/opt/conda/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 16, in <module>
    from modelscope.msdatasets import MsDataset
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import load_dataset_with_ctx
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 58, in <module>
    from huggingface_hub.hf_api import HfApi, RepoFile, RepoFolder
ImportError: cannot import name 'RepoFolder' from 'huggingface_hub.hf_api' (/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py)

**Comment by wenmengzhou** [comment]
seems datasets version is not compatible with corresponding huggingface_hub, try other version of huggingface_hub
