### ISSUE TITLE
py_sound_connect无法安装

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [modelscope/modelscope#884]
modelscope版本：1.15.0

运行CTC的demo程序：
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks


kws = pipeline(
    Tasks.keyword_spotting,
    model='damo/speech_dfsmn_kws_char_farfield_16k_nihaomiya')
# you can also use local file path
result = kws('https://modelscope.oss-cn-beijing.aliyuncs.com/test/audios/3ch_nihaomiya10.wav')
print(result)
```

报错：
```
2024-06-17 16:26:25,011 - modelscope - INFO - PyTorch version 1.10.2+cu102 Found.
2024-06-17 16:26:25,014 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2024-06-17 16:26:25,015 - modelscope - INFO - Loading ast index from C:\Users\24115\.cache\modelscope\ast_indexer
2024-06-17 16:26:25,129 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 81203c215ac348dce49ba68f25d9e3f8 and a total number of 980 components indexed
2024-06-17 16:26:27,142 - modelscope - WARNING - Model revision not specified, use revision: v1.1.3
2024-06-17 16:26:27,551 - modelscope - INFO - initiate model from C:\Users\24115\.cache\modelscope\hub\damo\speech_dfsmn_kws_char_farfield_16k_nihaomiya
2024-06-17 16:26:27,551 - modelscope - INFO - initiate model from location C:\Users\24115\.cache\modelscope\hub\damo\speech_dfsmn_kws_char_farfield_16k_nihaomiya.
2024-06-17 16:26:27,553 - modelscope - INFO - initialize model from C:\Users\24115\.cache\modelscope\hub\damo\speech_dfsmn_kws_char_farfield_16k_nihaomiya
Traceback (most recent call last):
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\models\audio\kws\farfield\model.py", line 49, in __init__
    import py_sound_connect
ModuleNotFoundError: No module named 'py_sound_connect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\pipelines\audio\kws_farfield_pipeline.py", line 38, in __init__
    super().__init__(model=model, **kwargs)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\pipelines\base.py", line 100, in __init__
    self.model = self.initiate_single_model(model, **kwargs)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: FSMNSeleNetV2Decorator: No module named 'py_sound_connect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/24115/Desktop/学习/ctc/1.py", line 5, in <module>
    kws = pipeline(
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Users\24115\.conda\envs\torch1\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ModuleNotFoundError: KWSFarfieldPipeline: FSMNSeleNetV2Decorator: No module named 'py_sound_connect'
```

应该是需要安装py_sound_connect这个库，但我使用pip install py_sound_connect无法安装该库

**Comment by wenmengzhou** [comment]
duplicated with #885
