### ISSUE TITLE
FileNotFoundError: Cannot find dataset meta-files, please fetch meta from modelscope hub.

### ISSUE THREAD

**Issue by ducanh841988** [modelscope/modelscope#907]
Before asking a question, make sure you have:

Searched the tutorial on modelscope [doc-site](https://modelscope.cn/docs)
Googled your question.
Searched related issues but cannot get the expected help.
The bug has not been fixed in the latest version.
Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Model hub related: @liuyhwangyh

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**General Question**
I try to load this dataset but it cause the below error:
https://www.modelscope.cn/datasets/Wente47/M2E
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anhle/opt/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/msdatasets/ms_dataset.py", line 316, in load
    dataset_inst = remote_dataloader_manager.load_dataset(
  File "/Users/anhle/opt/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader_manager.py", line 132, in load_dataset
    oss_downloader.process()
  File "/Users/anhle/opt/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 82, in process
    self._build()
  File "/Users/anhle/opt/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/msdatasets/data_loader/data_loader.py", line 109, in _build
    meta_manager.parse_dataset_structure()
  File "/Users/anhle/opt/anaconda3/envs/modelscope/lib/python3.8/site-packages/modelscope/msdatasets/meta/data_meta_manager.py", line 119, in parse_dataset_structure
    raise FileNotFoundError(
FileNotFoundError: Cannot find dataset meta-files, please fetch meta from modelscope hub.`
I use Version: 1.16.0. 
I try to search but there is no solution for this. Could you help on this @wangxingjun778

**Comment by slin000111** [comment]
Login before load this dataset as below:
```python
from modelscope import HubApi

api=HubApi()
api.login('YOUR_MODELSCOPE_SDK_ACCESS_TOKEN')
```
Then run the sample code on the dataset card to load this dataset, Wente47/M2E.
