### ISSUE TITLE
'scrfd is not in the exporters registry group face-detection

### ISSUE THREAD

**Issue by wq9** [modelscope/modelscope#940]
'scrfd is not in the exporters registry group face-detection

**To Reproduce**
Run following in python:
```python
from modelscope.exporters import Exporter
from modelscope.models import Model

model = Model.from_pretrained('damo/cv_resnet_facedetection_scrfd10gkps')
out = Exporter.from_model(model).export_onnx(output_dir='/home/ubuntu/models_data/scrfd', )
```
Output:
```
... - modelscope - INFO - loading model from /root/.cache/modelscope/hub/damo/cv_resnet_facedetection_scrfd10gkps/pytorch_model.bin
load checkpoint from local path: /root/.cache/modelscope/hub/damo/cv_resnet_facedetection_scrfd10gkps/pytorch_model.bin
... - modelscope - INFO - load model done
'scrfd is not in the exporters registry group face-detection. Please make sure the correct version of ModelScope library is used.'
"The exporting of model 'scrfd' with task: 'face-detection' is not supported currently."
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/base.py", line 52, in from_model
    exporter = build_exporter(export_cfg, task_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/builder.py", line 20, in build_exporter
    return build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'scrfd is not in the exporters registry group face-detection. Please make sure the correct version of ModelScope library is used.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/base.py", line 52, in from_model
    exporter = build_exporter(export_cfg, task_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/builder.py", line 20, in build_exporter
    return build_from_cfg(
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/usr/local/lib/python3.10/dist-packages/modelscope/utils/import_utils.py", line 475, in import_module
    importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/cv/face_detection_scrfd_exporter.py", line 7, in <module>
    import onnx
  File "/home/ubuntu/modelsservings/model_conversions/scrfd/onnx.py", line 5, in <module>
    out = Exporter.from_model(model).export_onnx(output_dir='/home/ubuntu/models_data/scrfd', )
  File "/usr/local/lib/python3.10/dist-packages/modelscope/exporters/base.py", line 55, in from_model
    raise KeyError(
KeyError: "The exporting of model 'scrfd' with task: 'face-detection' is not supported currently."
```

**Environments**
* OS: `22.04.1-Ubuntu`
* CPU: `Intel(R) Xeon(R) CPU @ 2.20GHz`
* Python: `3.10.12`
* modelscope: `1.17.0`
* mmdet: `2.28.2`
* mmcv-full: `1.7.2`
* torch: `2.3.1+cu121`

Please @ corresponding people according to your problem:
Model hub related: @liuyhwangyh

**Comment by slin000111** [comment]
The exporting of this model works.
```shell
torch                             2.3.0+cu121
mmcv-full                     1.7.0
mmdet                          2.28.2
modelscope                 1.17.0
```
