### ISSUE TITLE
模型训练无法存储checkpoint

### ISSUE THREAD

**Issue by jprorikon** [modelscope/modelscope#955]
在ubuntu 22.04 使用 modelscope 1.17.1 版本，用
https://modelscope.cn/models/iic/cv_LightweightEdge_ocr-recognitoin-general_damo
中所示的训练脚本尝试训练模型时
报如下错误
```
2024-08-23 09:22:29,099 - modelscope - INFO - Checkpoints will be saved to /tmp/tmp8gzabwkm
2024-08-23 09:22:29,099 - modelscope - INFO - Text logs will be saved to /tmp/tmp8gzabwkm
2024-08-23 09:22:34,874 - modelscope - INFO - epoch [1][50/108] lr: 1.000e-03, eta: 0:02:59, iter_time: 0.114, data_load_time: 0.063, memory: 2488, loss: 3.0732
2024-08-23 09:22:40,319 - modelscope - INFO - epoch [1][100/108]        lr: 1.000e-03, eta: 0:02:49, iter_time: 0.109, data_load_time: 0.064, memory: 2488, loss: 1.7033
Total test samples: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3432/3432 [00:08<00:00, 399.12it/s]
2024-08-23 09:22:51,627 - modelscope - INFO - Saving checkpoint at 1 epoch
Traceback (most recent call last):
  File "/home/liuzhaoyu/workspace/testlitetrain/test.py", line 94, in <module>
    trainer.train()
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/trainer.py", line 711, in train
    self.train_loop(self.train_dataloader)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/trainer.py", line 1243, in train_loop
    self.invoke_hook(TrainerStages.after_train_epoch)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/trainer.py", line 1395, in invoke_hook
    getattr(hook, fn_name)(self)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/hooks/checkpoint/checkpoint_hook.py", line 177, in after_train_epoch
    self._do_save(trainer, CheckpointStrategy.by_epoch)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/hooks/checkpoint/checkpoint_hook.py", line 160, in _do_save
    self._save_checkpoint(trainer, prefix)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/hooks/checkpoint/checkpoint_hook.py", line 227, in _save_checkpoint
    self.save_evaluate_results(trainer)
  File "/home/liuzhaoyu/workspace/testlitetrain/lite/lib/python3.10/site-packages/modelscope/trainers/hooks/checkpoint/checkpoint_hook.py", line 217, in save_evaluate_results
    f.write(json.dumps(trainer.metric_values))
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

其他包信息
```
.0
certifi                  2024.7.4
cffi                     1.17.0
charset-normalizer       3.3.2
comm                     0.2.2
crcmod                   1.7
cryptography             43.0.0
datasets                 2.21.0
debugpy                  1.8.5
decorator                5.1.1
dill                     0.3.8
edit-distance            1.0.6
exceptiongroup           1.2.2
executing                2.0.1
filelock                 3.15.4
frozenlist               1.4.1
fsspec                   2024.6.1
huggingface-hub          0.24.6
idna                     3.7
ipykernel                6.29.5
ipython                  8.26.0
jedi                     0.19.1
Jinja2                   3.1.4
jmespath                 0.10.0
jupyter_client           8.6.2
jupyter_core             5.7.2
lmdb                     1.5.1
MarkupSafe               2.1.5
matplotlib-inline        0.1.7
modelscope               1.17.1
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
nest-asyncio             1.6.0
networkx                 3.3
numpy                    2.1.0
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
oss2                     2.18.6
packaging                24.1
pandas                   2.2.2
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.4.0
pip                      22.0.2
platformdirs             4.2.2
prompt_toolkit           3.0.47
psutil                   6.0.0
ptyprocess               0.7.0
pure_eval                0.2.3
pyarrow                  17.0.0
pycparser                2.22
pycryptodome             3.20.0
Pygments                 2.18.0
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2
pyzmq                    26.1.1
requests                 2.32.3
setuptools               59.6.0
simplejson               3.19.3
six                      1.16.0
sortedcontainers         2.4.0
stack-data               0.6.3
sympy                    1.13.2
torch                    2.4.0
torchaudio               2.4.0
torchvision              0.19.0
tornado                  6.4.1
tqdm                     4.66.5
traitlets                5.14.3
triton                   3.0.0
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
wcwidth                  0.2.13
xxhash                   3.5.0
yarl                     1.9.4
```

**Comment by slin000111** [comment]
试试
