### ISSUE TITLE
使用自定义的数据集微调CN_CLIP模型，train程序中dataloader返回的batch_data 为空

### ISSUE THREAD

**Issue by LamperEin** [modelscope/modelscope#956]
采用本地自定义数据集微调CN_CLIP模型，程序报错，后面自行debug发现是trainer.py中dataloader返回的batch_data为空
程序报错如下：
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\MLProject\image-match-2024-2\cn_clip_finetune.py", line 148, in <module>
    trainer.train()
  File "D:\Anaconda\envs\myModelScope2\lib\site-packages\modelscope\trainers\trainer.py", line 711, in train
    self.train_loop(self.train_dataloader)
  File "D:\Anaconda\envs\myModelScope2\lib\site-packages\modelscope\trainers\trainer.py", line 1234, in train_loop
    self.train_step(self.model, data_batch)
  File "D:\Anaconda\envs\myModelScope2\lib\site-packages\modelscope\trainers\multi_modal\clip\clip_trainer.py", line 208, in train_step
    loss = get_loss(model_outputs, self.loss_img, self.loss_txt,
  File "D:\Anaconda\envs\myModelScope2\lib\site-packages\modelscope\trainers\multi_modal\clip\clip_trainer_utils.py", line 93, in get_loss
    logits_per_image = logit_scale * image_features @ text_features.t()
TypeError: unsupported operand type(s) for *: 'Tensor' and 'NoneType'

微调代码如下（无法上传.py文件）：
[微调代码.txt](https://github.com/user-attachments/files/16732532/default.txt)

环境：

modelscope version: 1.17.1
torch version: 2.4.0+cu118
cuda version 12.2
is_cuda_available: True

Please @ corresponding people according to your problem:

Model related: @wenmengzhou @tastelikefeet

Dataset releated: @wangxingjun778

Finetune related: @tastelikefeet  @Jintao-Huang

Pipeline related: @Firmament-cyou @wenmengzhou

**Comment by slin000111** [comment]
`print(next(iter(train_dataset)))`对比一下本地数据和muge数据集格式
