### ISSUE TITLE
单机多卡："trying to initialize the default process group " "twice!"

### ISSUE THREAD

**Issue by wylqq312715289** [modelscope/modelscope#98]
单机多卡训练gpt-3 报："trying to initialize the default process group " "twice!" 错误

**Comment by Stepuuu** [comment]
我也是，请问解决了吗

**Comment by wenmengzhou** [comment]
具体报错信息贴一下？

**Comment by Stepuuu** [comment]
`(dupa4) sy@ti2081:~/code/DUPA-ASA/DDP$ python -m torch.distributed.launch --nproc_per_node 4 run.py --model bert --data IMDB
/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    x = import_module('models.' + model_name)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sy/code/DUPA-ASA/DDP/models/bert.py", line 6, in <module>
    a=import_module('run.py')
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sy/code/DUPA-ASA/DDP/run.py", line 23, in <module>
    init_process_group(backend='nccl')  # nccl是GPU设备上最快、最推荐的后端
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 563, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    x = import_module('models.' + model_name)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sy/code/DUPA-ASA/DDP/models/bert.py", line 6, in <module>
    a=import_module('run.py')
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sy/code/DUPA-ASA/DDP/run.py", line 23, in <module>
    init_process_group(backend='nccl')  # nccl是GPU设备上最快、最推荐的后端
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 563, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
Traceback (most recent call last):
  File "run.py", line 31, in <module>
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    x = import_module('models.' + model_name)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    x = import_module('models.' + model_name)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "/home/sy/code/DUPA-ASA/DDP/models/bert.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sy/code/DUPA-ASA/DDP/models/bert.py", line 6, in <module>
    a=import_module('run.py')
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    a=import_module('run.py')
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "/home/sy/code/DUPA-ASA/DDP/run.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/sy/code/DUPA-ASA/DDP/run.py", line 23, in <module>
init_process_group(backend='nccl')  # nccl是GPU设备上最快、最推荐的后端
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 563, in init_process_group
    init_process_group(backend='nccl')  # nccl是GPU设备上最快、最推荐的后端
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 563, in init_process_group
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
    raise RuntimeError("trying to initialize the default process group " "twice!")
RuntimeError: trying to initialize the default process group twice!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11865) of binary: /home/sy/.conda/envs/dupa4/bin/python
Traceback (most recent call last):
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sy/.conda/envs/dupa4/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-09_11:18:33
  host      : ti2081
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11866)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-09_11:18:33
  host      : ti2081
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 11867)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-11-09_11:18:33
  host      : ti2081
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 11868)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-09_11:18:33
  host      : ti2081
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11865)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
`
