### ISSUE TITLE
MsDataset.load()modelscope支持的数据集失败

### ISSUE THREAD

**Issue by JeremySun1224** [modelscope/modelscope#983]
modelscope version 1.18.0
```python
from modelscope.msdatasets import MsDataset
ds = MsDataset.load('wangxingjun778/alpaca-gpt4-data-zh', subset_name='default', split='train')
print(ds)
```

报错
```python
2024-09-10 11:28:07,023 - modelscope - ERROR - >> Error loading wangxingjun778/alpaca-gpt4-data-zh: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 1369, in load_dataset_with_ctx
    dataset_res = DatasetsWrapperHF.load_dataset(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 938, in load_dataset
    builder_instance = DatasetsWrapperHF.load_dataset_builder(
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 1065, in load_dataset_builder
    dataset_module = DatasetsWrapperHF.dataset_module_factory(
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 1326, in dataset_module_factory
    raise e1 from None
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 1301, in dataset_module_factory
    ).get_module()
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 592, in get_module_without_script
    patterns = _get_data_patterns(
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 531, in _get_data_patterns
    return _get_data_files_patterns(resolver)
  File "/opt/conda/lib/python3.10/site-packages/datasets/data_files.py", line 295, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/opt/conda/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 400, in _resolve_pattern
    tmp_file_paths = fs.glob(pattern, detail=True, **glob_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 417, in glob
    return super().glob(path, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/fsspec/spec.py", line 602, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 430, in find
    return super().find(
  File "/opt/conda/lib/python3.10/site-packages/fsspec/spec.py", line 493, in find
    out[path] = self.info(path)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 517, in info
    last_commit = self._api.list_repo_commits(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3056, in list_repo_commits
    return [
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3056, in <listcomp>
    return [
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_pagination.py", line 38, in paginate
    yield from r.json()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

该数据集modelscope是支持的
[wangxingjun778/alpaca-gpt4-data-zh](https://modelscope.cn/datasets/wangxingjun778/alpaca-gpt4-data-zh)

**Comment by ioo0s** [comment]
我遇到过同样的问题，造成原因是因为这份数据集混用了json 和csv数据，加载的时候默认将CSV按照json的格式decode了。
目前我的解决方法：
1. 按照官方加载方法：下载数据集 指定当前要加载数据集的绝对路径
2. 修改数据集（可能需要fork一份）统一数据集格式，要么都json 要么都csv。
3. 指定加载格式load("csv", data_dir=这里指定具体的数据集路径)
